/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_admin (void);
GtkWidget* create_adherent (void);
GtkWidget* create_nutritionniste (void);
GtkWidget* create_dieteticien (void);
GtkWidget* create_kine (void);
GtkWidget* create_coach (void);
GtkWidget* create_window2 (void);
GtkWidget* create_rendezvous (void);
GtkWidget* create_info (void);
GtkWidget* create_information (void);
GtkWidget* create_modifierinfo (void);
GtkWidget* create_GestionCompte (void);
GtkWidget* create_AjouterCompte (void);
GtkWidget* create_annulation (void);
