/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *label8;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *button1;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image7;
  GtkWidget *label111;
  GtkWidget *button3;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image8;
  GtkWidget *label112;
  GtkWidget *image6;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window1, 490, 490);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 184, 176);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_max_length (GTK_ENTRY (entry1), 10);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);
  gtk_entry_set_activates_default (GTK_ENTRY (entry1), TRUE);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 184, 232);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_max_length (GTK_ENTRY (entry2), 8);
  gtk_entry_set_visibility (GTK_ENTRY (entry2), FALSE);
  gtk_entry_set_activates_default (GTK_ENTRY (entry2), TRUE);

  label8 = gtk_label_new ("");
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed1), label8, 112, 304);
  gtk_widget_set_size_request (label8, 233, 25);

  label1 = gtk_label_new (_("user name:"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 72, 160);
  gtk_widget_set_size_request (label1, 112, 56);

  label2 = gtk_label_new (_("Password:"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 80, 208);
  gtk_widget_set_size_request (label2, 104, 80);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 56, 440);
  gtk_widget_set_size_request (button1, 112, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button1), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image7 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox5), image7, FALSE, FALSE, 0);

  label111 = gtk_label_new_with_mnemonic (_("login"));
  gtk_widget_show (label111);
  gtk_box_pack_start (GTK_BOX (hbox5), label111, FALSE, FALSE, 0);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed1), button3, 296, 440);
  gtk_widget_set_size_request (button3, 134, 33);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button3), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image8 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox6), image8, FALSE, FALSE, 0);

  label112 = gtk_label_new_with_mnemonic (_("close"));
  gtk_widget_show (label112);
  gtk_box_pack_start (GTK_BOX (hbox6), label112, FALSE, FALSE, 0);

  image6 = create_pixmap (window1, "outlook.png");
  gtk_widget_show (image6);
  gtk_fixed_put (GTK_FIXED (fixed1), image6, 0, 0);
  gtk_widget_set_size_request (image6, 500, 500);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window1, label8, "label8");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window1, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window1, image7, "image7");
  GLADE_HOOKUP_OBJECT (window1, label111, "label111");
  GLADE_HOOKUP_OBJECT (window1, button3, "button3");
  GLADE_HOOKUP_OBJECT (window1, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window1, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window1, image8, "image8");
  GLADE_HOOKUP_OBJECT (window1, label112, "label112");
  GLADE_HOOKUP_OBJECT (window1, image6, "image6");

  return window1;
}

GtkWidget*
create_admin (void)
{
  GtkWidget *admin;
  GtkWidget *fixed15;
  GtkWidget *button6n;
  GtkWidget *button2n;

  admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (admin), _("Admin"));

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (admin), fixed15);

  button6n = gtk_button_new_with_mnemonic (_("gestion du compte"));
  gtk_widget_show (button6n);
  gtk_fixed_put (GTK_FIXED (fixed15), button6n, 168, 144);
  gtk_widget_set_size_request (button6n, 208, 41);

  button2n = gtk_button_new_with_mnemonic (_("profile admin"));
  gtk_widget_show (button2n);
  gtk_fixed_put (GTK_FIXED (fixed15), button2n, 168, 72);
  gtk_widget_set_size_request (button2n, 206, 41);

  g_signal_connect ((gpointer) button6n, "clicked",
                    G_CALLBACK (on_button6n_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2n, "clicked",
                    G_CALLBACK (on_button2n_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (admin, admin, "admin");
  GLADE_HOOKUP_OBJECT (admin, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (admin, button6n, "button6n");
  GLADE_HOOKUP_OBJECT (admin, button2n, "button2n");

  return admin;
}

GtkWidget*
create_adherent (void)
{
  GtkWidget *adherent;
  GtkWidget *fixed3;
  GtkWidget *fixed8;
  GtkWidget *poid;
  GtkWidget *ville;
  GtkWidget *numtel;
  GtkWidget *daten;
  GtkWidget *nom;
  GtkWidget *sex;
  GtkWidget *age;
  GtkWidget *prenon;
  GtkWidget *button4;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label13;
  GtkWidget *image9;
  GtkWidget *button10;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image10;
  GtkWidget *label113;
  GtkWidget *button13;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image11;
  GtkWidget *label114;

  adherent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (adherent, 490, 490);
  gtk_window_set_title (GTK_WINDOW (adherent), _("adherent"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (adherent), fixed3);
  gtk_widget_set_size_request (fixed3, 600, 600);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_fixed_put (GTK_FIXED (fixed3), fixed8, 416, 288);
  gtk_widget_set_size_request (fixed8, 50, 50);

  poid = gtk_label_new ("");
  gtk_widget_show (poid);
  gtk_fixed_put (GTK_FIXED (fixed3), poid, 312, 240);
  gtk_widget_set_size_request (poid, 49, 17);

  ville = gtk_label_new ("");
  gtk_widget_show (ville);
  gtk_fixed_put (GTK_FIXED (fixed3), ville, 312, 272);
  gtk_widget_set_size_request (ville, 49, 17);

  numtel = gtk_label_new ("");
  gtk_widget_show (numtel);
  gtk_fixed_put (GTK_FIXED (fixed3), numtel, 312, 304);
  gtk_widget_set_size_request (numtel, 96, 16);

  daten = gtk_label_new ("");
  gtk_widget_show (daten);
  gtk_fixed_put (GTK_FIXED (fixed3), daten, 312, 200);
  gtk_widget_set_size_request (daten, 128, 16);

  nom = gtk_label_new ("");
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed3), nom, 312, 48);
  gtk_widget_set_size_request (nom, 49, 17);

  sex = gtk_label_new ("");
  gtk_widget_show (sex);
  gtk_fixed_put (GTK_FIXED (fixed3), sex, 312, 160);
  gtk_widget_set_size_request (sex, 49, 17);

  age = gtk_label_new ("");
  gtk_widget_show (age);
  gtk_fixed_put (GTK_FIXED (fixed3), age, 312, 112);
  gtk_widget_set_size_request (age, 49, 17);

  prenon = gtk_label_new ("");
  gtk_widget_show (prenon);
  gtk_fixed_put (GTK_FIXED (fixed3), prenon, 312, 16);
  gtk_widget_set_size_request (prenon, 109, 64);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed3), button4, 192, 384);
  gtk_widget_set_size_request (button4, 112, 33);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button4), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("retourner "));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox1), label13, FALSE, FALSE, 0);

  image9 = create_pixmap (adherent, "outlook.png");
  gtk_widget_show (image9);
  gtk_fixed_put (GTK_FIXED (fixed3), image9, 0, 0);
  gtk_widget_set_size_request (image9, 500, 500);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed3), button10, 104, 264);
  gtk_widget_set_size_request (button10, 288, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button10), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image10 = gtk_image_new_from_stock ("gtk-file", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox7), image10, FALSE, FALSE, 0);

  label113 = gtk_label_new_with_mnemonic (_("mes rendez vous"));
  gtk_widget_show (label113);
  gtk_box_pack_start (GTK_BOX (hbox7), label113, FALSE, FALSE, 0);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed3), button13, 104, 192);
  gtk_widget_set_size_request (button13, 288, 48);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button13), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image11 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox8), image11, FALSE, FALSE, 0);

  label114 = gtk_label_new_with_mnemonic (_("informations personnelles"));
  gtk_widget_show (label114);
  gtk_box_pack_start (GTK_BOX (hbox8), label114, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);
  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (on_button10_clicked),
                    NULL);
  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (on_button13_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (adherent, adherent, "adherent");
  GLADE_HOOKUP_OBJECT (adherent, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (adherent, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (adherent, poid, "poid");
  GLADE_HOOKUP_OBJECT (adherent, ville, "ville");
  GLADE_HOOKUP_OBJECT (adherent, numtel, "numtel");
  GLADE_HOOKUP_OBJECT (adherent, daten, "daten");
  GLADE_HOOKUP_OBJECT (adherent, nom, "nom");
  GLADE_HOOKUP_OBJECT (adherent, sex, "sex");
  GLADE_HOOKUP_OBJECT (adherent, age, "age");
  GLADE_HOOKUP_OBJECT (adherent, prenon, "prenon");
  GLADE_HOOKUP_OBJECT (adherent, button4, "button4");
  GLADE_HOOKUP_OBJECT (adherent, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (adherent, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (adherent, image1, "image1");
  GLADE_HOOKUP_OBJECT (adherent, label13, "label13");
  GLADE_HOOKUP_OBJECT (adherent, image9, "image9");
  GLADE_HOOKUP_OBJECT (adherent, button10, "button10");
  GLADE_HOOKUP_OBJECT (adherent, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (adherent, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (adherent, image10, "image10");
  GLADE_HOOKUP_OBJECT (adherent, label113, "label113");
  GLADE_HOOKUP_OBJECT (adherent, button13, "button13");
  GLADE_HOOKUP_OBJECT (adherent, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (adherent, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (adherent, image11, "image11");
  GLADE_HOOKUP_OBJECT (adherent, label114, "label114");

  return adherent;
}

GtkWidget*
create_nutritionniste (void)
{
  GtkWidget *nutritionniste;
  GtkWidget *fixed4;
  GtkWidget *label5;

  nutritionniste = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (nutritionniste), _("nutritionniste"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (nutritionniste), fixed4);

  label5 = gtk_label_new (_(" nutritionniste"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed4), label5, 40, 0);
  gtk_widget_set_size_request (label5, 312, 176);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (nutritionniste, nutritionniste, "nutritionniste");
  GLADE_HOOKUP_OBJECT (nutritionniste, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (nutritionniste, label5, "label5");

  return nutritionniste;
}

GtkWidget*
create_dieteticien (void)
{
  GtkWidget *dieteticien;
  GtkWidget *fixed5;
  GtkWidget *label11;

  dieteticien = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (dieteticien), _("dieteicien"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (dieteticien), fixed5);

  label11 = gtk_label_new (_(" dietecien"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed5), label11, 96, 0);
  gtk_widget_set_size_request (label11, 240, 216);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dieteticien, dieteticien, "dieteticien");
  GLADE_HOOKUP_OBJECT (dieteticien, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (dieteticien, label11, "label11");

  return dieteticien;
}

GtkWidget*
create_kine (void)
{
  GtkWidget *kine;
  GtkWidget *fixed6;
  GtkWidget *label7;

  kine = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (kine), _("kine"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (kine), fixed6);

  label7 = gtk_label_new (_(" kine"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed6), label7, 64, 0);
  gtk_widget_set_size_request (label7, 264, 224);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (kine, kine, "kine");
  GLADE_HOOKUP_OBJECT (kine, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (kine, label7, "label7");

  return kine;
}

GtkWidget*
create_coach (void)
{
  GtkWidget *coach;
  GtkWidget *fixed7;
  GtkWidget *label9;
  GtkWidget *label10;

  coach = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (coach), _("window2"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (coach), fixed7);

  label9 = gtk_label_new ("");
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed7), label9, 80, 80);
  gtk_widget_set_size_request (label9, 296, 216);

  label10 = gtk_label_new (_(" coach"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed7), label10, 48, 48);
  gtk_widget_set_size_request (label10, 288, 152);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (coach, coach, "coach");
  GLADE_HOOKUP_OBJECT (coach, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (coach, label9, "label9");
  GLADE_HOOKUP_OBJECT (coach, label10, "label10");

  return coach;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *label12;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  label12 = gtk_label_new (_("label12"));
  gtk_widget_show (label12);
  gtk_container_add (GTK_CONTAINER (window2), label12);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, label12, "label12");

  return window2;
}

GtkWidget*
create_rendezvous (void)
{
  GtkWidget *rendezvous;
  GtkWidget *fixed11;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *label88;
  GtkWidget *label34;
  GtkWidget *label36;
  GtkWidget *label33;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *button9;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label31;
  GtkWidget *button8;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label32;
  GtkWidget *combobox2;
  GtkWidget *combobox1;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview23;
  GtkWidget *image20;

  rendezvous = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (rendezvous, 490, 490);
  gtk_window_set_title (GTK_WINDOW (rendezvous), _("rendez vous"));
  gtk_window_set_default_size (GTK_WINDOW (rendezvous), 500, 500);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (rendezvous), fixed11);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbutton1, 144, 145);
  gtk_widget_set_size_request (spinbutton1, 70, 34);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbutton2, 288, 145);
  gtk_widget_set_size_request (spinbutton2, 70, 34);

  spinbutton3_adj = gtk_adjustment_new (2018, 2018, 2050, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbutton3, 136, 187);
  gtk_widget_set_size_request (spinbutton3, 70, 34);

  label88 = gtk_label_new ("");
  gtk_widget_show (label88);
  gtk_fixed_put (GTK_FIXED (fixed11), label88, 29, 295);
  gtk_widget_set_size_request (label88, 512, 33);

  label34 = gtk_label_new (_("jour:"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed11), label34, 71, 144);
  gtk_widget_set_size_request (label34, 64, 33);

  label36 = gtk_label_new (_("mois:"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed11), label36, 221, 144);
  gtk_widget_set_size_request (label36, 73, 33);

  label33 = gtk_label_new (_("Avec le:"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed11), label33, 152, 97);
  gtk_widget_set_size_request (label33, 65, 25);

  label37 = gtk_label_new (_("ann\303\251e:"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed11), label37, 80, 191);
  gtk_widget_set_size_request (label37, 49, 17);

  label38 = gtk_label_new (_("heure:"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed11), label38, 221, 190);
  gtk_widget_set_size_request (label38, 65, 33);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed11), button9, 280, 434);
  gtk_widget_set_size_request (button9, 96, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button9), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox3), label31, FALSE, FALSE, 0);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed11), button8, 104, 433);
  gtk_widget_set_size_request (button8, 88, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button8), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox4), label32, FALSE, FALSE, 0);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed11), combobox2, 280, 190);
  gtk_widget_set_size_request (combobox2, 101, 33);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("8h>12h"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("14h>18h"));

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed11), combobox1, 223, 93);
  gtk_widget_set_size_request (combobox1, 101, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("kine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("coach"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("nutritionniste"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("dietitian"));

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_fixed_put (GTK_FIXED (fixed11), scrolledwindow2, 72, 232);
  gtk_widget_set_size_request (scrolledwindow2, 350, 180);

  treeview23 = gtk_tree_view_new ();
  gtk_widget_show (treeview23);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview23);

  image20 = create_pixmap (rendezvous, "outlook.png");
  gtk_widget_show (image20);
  gtk_fixed_put (GTK_FIXED (fixed11), image20, 0, 0);
  gtk_widget_set_size_request (image20, 490, 490);

  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_button9_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_button8_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (rendezvous, rendezvous, "rendezvous");
  GLADE_HOOKUP_OBJECT (rendezvous, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (rendezvous, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (rendezvous, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (rendezvous, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (rendezvous, label88, "label88");
  GLADE_HOOKUP_OBJECT (rendezvous, label34, "label34");
  GLADE_HOOKUP_OBJECT (rendezvous, label36, "label36");
  GLADE_HOOKUP_OBJECT (rendezvous, label33, "label33");
  GLADE_HOOKUP_OBJECT (rendezvous, label37, "label37");
  GLADE_HOOKUP_OBJECT (rendezvous, label38, "label38");
  GLADE_HOOKUP_OBJECT (rendezvous, button9, "button9");
  GLADE_HOOKUP_OBJECT (rendezvous, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (rendezvous, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (rendezvous, image3, "image3");
  GLADE_HOOKUP_OBJECT (rendezvous, label31, "label31");
  GLADE_HOOKUP_OBJECT (rendezvous, button8, "button8");
  GLADE_HOOKUP_OBJECT (rendezvous, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (rendezvous, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (rendezvous, image4, "image4");
  GLADE_HOOKUP_OBJECT (rendezvous, label32, "label32");
  GLADE_HOOKUP_OBJECT (rendezvous, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (rendezvous, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (rendezvous, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (rendezvous, treeview23, "treeview23");
  GLADE_HOOKUP_OBJECT (rendezvous, image20, "image20");

  return rendezvous;
}

GtkWidget*
create_info (void)
{
  GtkWidget *info;
  GtkWidget *fixed12;
  GtkWidget *treeview1;
  GtkWidget *ajouter;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image16;
  GtkWidget *label117;
  GtkWidget *button11;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image15;
  GtkWidget *label116;
  GtkWidget *image13;
  GtkWidget *button191;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image14;
  GtkWidget *label115;

  info = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (info, 490, 490);
  gtk_window_set_title (GTK_WINDOW (info), _("mes rendez vous"));

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (info), fixed12);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed12), treeview1, 56, 144);
  gtk_widget_set_size_request (treeview1, 370, 200);
  gtk_container_set_border_width (GTK_CONTAINER (treeview1), 2);

  ajouter = gtk_button_new ();
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed12), ajouter, 80, 432);
  gtk_widget_set_size_request (ajouter, 328, 32);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (ajouter), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image16 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox11), image16, FALSE, FALSE, 0);

  label117 = gtk_label_new_with_mnemonic (_("ajouter un rendez vous"));
  gtk_widget_show (label117);
  gtk_box_pack_start (GTK_BOX (hbox11), label117, FALSE, FALSE, 0);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed12), button11, 256, 368);
  gtk_widget_set_size_request (button11, 120, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button11), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image15 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox10), image15, FALSE, FALSE, 0);

  label116 = gtk_label_new_with_mnemonic (_("retourner"));
  gtk_widget_show (label116);
  gtk_box_pack_start (GTK_BOX (hbox10), label116, FALSE, FALSE, 0);

  image13 = create_pixmap (info, "outlook.png");
  gtk_widget_show (image13);
  gtk_fixed_put (GTK_FIXED (fixed12), image13, 0, 0);
  gtk_widget_set_size_request (image13, 490, 490);

  button191 = gtk_button_new ();
  gtk_widget_show (button191);
  gtk_fixed_put (GTK_FIXED (fixed12), button191, 83, 368);
  gtk_widget_set_size_request (button191, 104, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button191), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image14 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox9), image14, FALSE, FALSE, 0);

  label115 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label115);
  gtk_box_pack_start (GTK_BOX (hbox9), label115, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_button11_clicked),
                    NULL);
  g_signal_connect ((gpointer) button191, "clicked",
                    G_CALLBACK (on_button191_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (info, info, "info");
  GLADE_HOOKUP_OBJECT (info, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (info, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (info, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (info, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (info, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (info, image16, "image16");
  GLADE_HOOKUP_OBJECT (info, label117, "label117");
  GLADE_HOOKUP_OBJECT (info, button11, "button11");
  GLADE_HOOKUP_OBJECT (info, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (info, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (info, image15, "image15");
  GLADE_HOOKUP_OBJECT (info, label116, "label116");
  GLADE_HOOKUP_OBJECT (info, image13, "image13");
  GLADE_HOOKUP_OBJECT (info, button191, "button191");
  GLADE_HOOKUP_OBJECT (info, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (info, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (info, image14, "image14");
  GLADE_HOOKUP_OBJECT (info, label115, "label115");

  return info;
}

GtkWidget*
create_information (void)
{
  GtkWidget *information;
  GtkWidget *fixed13;
  GtkWidget *button14;
  GtkWidget *button15;
  GtkWidget *treeview22;

  information = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (information), _("window3"));

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (information), fixed13);

  button14 = gtk_button_new_with_mnemonic (_("retourner"));
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed13), button14, 272, 232);
  gtk_widget_set_size_request (button14, 78, 33);

  button15 = gtk_button_new_with_mnemonic (_("ajouter/modifier"));
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed13), button15, 56, 232);
  gtk_widget_set_size_request (button15, 136, 32);

  treeview22 = gtk_tree_view_new ();
  gtk_widget_show (treeview22);
  gtk_fixed_put (GTK_FIXED (fixed13), treeview22, 56, 16);
  gtk_widget_set_size_request (treeview22, 300, 200);

  g_signal_connect ((gpointer) button14, "clicked",
                    G_CALLBACK (on_button14_clicked),
                    NULL);
  g_signal_connect ((gpointer) button15, "clicked",
                    G_CALLBACK (on_button15_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (information, information, "information");
  GLADE_HOOKUP_OBJECT (information, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (information, button14, "button14");
  GLADE_HOOKUP_OBJECT (information, button15, "button15");
  GLADE_HOOKUP_OBJECT (information, treeview22, "treeview22");

  return information;
}

GtkWidget*
create_modifierinfo (void)
{
  GtkWidget *modifierinfo;
  GtkWidget *fixed14;
  GtkWidget *entry1000;
  GtkWidget *entry2000;
  GtkWidget *entry3000;
  GtkWidget *entry5000;
  GtkWidget *entry6000;
  GtkWidget *entry7000;
  GtkWidget *label94;
  GtkWidget *label95;
  GtkWidget *button17;
  GtkWidget *button16;
  GtkWidget *label93;
  GtkWidget *label92;
  GtkWidget *label91;
  GtkWidget *label90;
  GtkWidget *label89;
  GtkWidget *combobox4000;
  GtkWidget *image12;

  modifierinfo = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (modifierinfo, 490, 490);
  gtk_window_set_title (GTK_WINDOW (modifierinfo), _("window4"));

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (modifierinfo), fixed14);

  entry1000 = gtk_entry_new ();
  gtk_widget_show (entry1000);
  gtk_fixed_put (GTK_FIXED (fixed14), entry1000, 152, 112);
  gtk_widget_set_size_request (entry1000, 172, 34);
  gtk_entry_set_max_length (GTK_ENTRY (entry1000), 10);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1000), 8226);
  gtk_entry_set_activates_default (GTK_ENTRY (entry1000), TRUE);

  entry2000 = gtk_entry_new ();
  gtk_widget_show (entry2000);
  gtk_fixed_put (GTK_FIXED (fixed14), entry2000, 152, 160);
  gtk_widget_set_size_request (entry2000, 172, 26);
  gtk_entry_set_max_length (GTK_ENTRY (entry2000), 10);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2000), 8226);
  gtk_entry_set_activates_default (GTK_ENTRY (entry2000), TRUE);

  entry3000 = gtk_entry_new ();
  gtk_widget_show (entry3000);
  gtk_fixed_put (GTK_FIXED (fixed14), entry3000, 152, 208);
  gtk_widget_set_size_request (entry3000, 172, 26);
  gtk_entry_set_max_length (GTK_ENTRY (entry3000), 2);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3000), 8226);

  entry5000 = gtk_entry_new ();
  gtk_widget_show (entry5000);
  gtk_fixed_put (GTK_FIXED (fixed14), entry5000, 152, 296);
  gtk_widget_set_size_request (entry5000, 172, 26);
  gtk_entry_set_max_length (GTK_ENTRY (entry5000), 10);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5000), 8226);

  entry6000 = gtk_entry_new ();
  gtk_widget_show (entry6000);
  gtk_fixed_put (GTK_FIXED (fixed14), entry6000, 152, 336);
  gtk_widget_set_size_request (entry6000, 172, 26);
  gtk_entry_set_max_length (GTK_ENTRY (entry6000), 8);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6000), 8226);

  entry7000 = gtk_entry_new ();
  gtk_widget_show (entry7000);
  gtk_fixed_put (GTK_FIXED (fixed14), entry7000, 152, 376);
  gtk_widget_set_size_request (entry7000, 172, 26);
  gtk_entry_set_max_length (GTK_ENTRY (entry7000), 20);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7000), 8226);

  label94 = gtk_label_new (_("tel:"));
  gtk_widget_show (label94);
  gtk_fixed_put (GTK_FIXED (fixed14), label94, 77, 342);
  gtk_widget_set_size_request (label94, 49, 17);

  label95 = gtk_label_new (_("email:"));
  gtk_widget_show (label95);
  gtk_fixed_put (GTK_FIXED (fixed14), label95, 75, 382);
  gtk_widget_set_size_request (label95, 49, 17);

  button17 = gtk_button_new_with_mnemonic (_("ajouter/modifer"));
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed14), button17, 56, 432);
  gtk_widget_set_size_request (button17, 144, 32);

  button16 = gtk_button_new_with_mnemonic (_("retourner"));
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed14), button16, 248, 432);
  gtk_widget_set_size_request (button16, 96, 32);

  label93 = gtk_label_new (_("adresse:"));
  gtk_widget_show (label93);
  gtk_fixed_put (GTK_FIXED (fixed14), label93, 56, 300);
  gtk_widget_set_size_request (label93, 80, 17);

  label92 = gtk_label_new (_("sex:"));
  gtk_widget_show (label92);
  gtk_fixed_put (GTK_FIXED (fixed14), label92, 72, 252);
  gtk_widget_set_size_request (label92, 49, 17);

  label91 = gtk_label_new (_("age:"));
  gtk_widget_show (label91);
  gtk_fixed_put (GTK_FIXED (fixed14), label91, 74, 213);
  gtk_widget_set_size_request (label91, 49, 17);

  label90 = gtk_label_new (_("prenon:"));
  gtk_widget_show (label90);
  gtk_fixed_put (GTK_FIXED (fixed14), label90, 50, 165);
  gtk_widget_set_size_request (label90, 81, 17);

  label89 = gtk_label_new (_("nom:"));
  gtk_widget_show (label89);
  gtk_fixed_put (GTK_FIXED (fixed14), label89, 57, 120);
  gtk_widget_set_size_request (label89, 81, 17);

  combobox4000 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (combobox4000);
  gtk_fixed_put (GTK_FIXED (fixed14), combobox4000, 176, 240);
  gtk_widget_set_size_request (combobox4000, 96, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4000), _("male"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4000), _("female"));

  image12 = create_pixmap (modifierinfo, "outlook.png");
  gtk_widget_show (image12);
  gtk_fixed_put (GTK_FIXED (fixed14), image12, 0, 0);
  gtk_widget_set_size_request (image12, 490, 490);

  g_signal_connect ((gpointer) modifierinfo, "show",
                    G_CALLBACK (on_modifierinfo_show),
                    NULL);
  g_signal_connect ((gpointer) button17, "clicked",
                    G_CALLBACK (on_button17_clicked),
                    NULL);
  g_signal_connect ((gpointer) button16, "clicked",
                    G_CALLBACK (on_button16_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifierinfo, modifierinfo, "modifierinfo");
  GLADE_HOOKUP_OBJECT (modifierinfo, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (modifierinfo, entry1000, "entry1000");
  GLADE_HOOKUP_OBJECT (modifierinfo, entry2000, "entry2000");
  GLADE_HOOKUP_OBJECT (modifierinfo, entry3000, "entry3000");
  GLADE_HOOKUP_OBJECT (modifierinfo, entry5000, "entry5000");
  GLADE_HOOKUP_OBJECT (modifierinfo, entry6000, "entry6000");
  GLADE_HOOKUP_OBJECT (modifierinfo, entry7000, "entry7000");
  GLADE_HOOKUP_OBJECT (modifierinfo, label94, "label94");
  GLADE_HOOKUP_OBJECT (modifierinfo, label95, "label95");
  GLADE_HOOKUP_OBJECT (modifierinfo, button17, "button17");
  GLADE_HOOKUP_OBJECT (modifierinfo, button16, "button16");
  GLADE_HOOKUP_OBJECT (modifierinfo, label93, "label93");
  GLADE_HOOKUP_OBJECT (modifierinfo, label92, "label92");
  GLADE_HOOKUP_OBJECT (modifierinfo, label91, "label91");
  GLADE_HOOKUP_OBJECT (modifierinfo, label90, "label90");
  GLADE_HOOKUP_OBJECT (modifierinfo, label89, "label89");
  GLADE_HOOKUP_OBJECT (modifierinfo, combobox4000, "combobox4000");
  GLADE_HOOKUP_OBJECT (modifierinfo, image12, "image12");

  return modifierinfo;
}

GtkWidget*
create_GestionCompte (void)
{
  GtkWidget *GestionCompte;
  GtkWidget *fixed16;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1n;
  GtkWidget *button7n;

  GestionCompte = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (GestionCompte), _("GestionCompte"));

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (GestionCompte), fixed16);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed16), scrolledwindow1, 112, 72);
  gtk_widget_set_size_request (scrolledwindow1, 500, 300);

  treeview1n = gtk_tree_view_new ();
  gtk_widget_show (treeview1n);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1n);

  button7n = gtk_button_new_with_mnemonic (_("interface ajoute"));
  gtk_widget_show (button7n);
  gtk_fixed_put (GTK_FIXED (fixed16), button7n, 112, 424);
  gtk_widget_set_size_request (button7n, 184, 41);

  g_signal_connect ((gpointer) button7n, "clicked",
                    G_CALLBACK (on_button7n_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GestionCompte, GestionCompte, "GestionCompte");
  GLADE_HOOKUP_OBJECT (GestionCompte, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (GestionCompte, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (GestionCompte, treeview1n, "treeview1n");
  GLADE_HOOKUP_OBJECT (GestionCompte, button7n, "button7n");

  return GestionCompte;
}

GtkWidget*
create_AjouterCompte (void)
{
  GtkWidget *AjouterCompte;
  GtkWidget *fixed17;
  GtkWidget *entry8n;
  GtkWidget *entry9n;
  GtkWidget *entry7005;
  GtkWidget *label97;
  GtkWidget *label98;
  GtkWidget *label99;
  GtkWidget *combobox2n;
  GtkWidget *button8n;
  GtkWidget *label100;
  GtkWidget *label28n;
  GtkWidget *label29n;
  GtkWidget *label30n;
  GtkWidget *fixed18;
  GtkWidget *entry7006;
  GtkWidget *entry7007;
  GtkWidget *entry7008;
  GtkWidget *label104;
  GtkWidget *label105;
  GtkWidget *label106;
  GtkWidget *combobox4001;
  GtkWidget *button18;
  GtkWidget *label107;
  GtkWidget *label108;
  GtkWidget *label109;
  GtkWidget *label110;
  GtkWidget *label31n;

  AjouterCompte = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (AjouterCompte), _("AjouterCompte"));

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_container_add (GTK_CONTAINER (AjouterCompte), fixed17);

  entry8n = gtk_entry_new ();
  gtk_widget_show (entry8n);
  gtk_fixed_put (GTK_FIXED (fixed17), entry8n, 136, 24);
  gtk_widget_set_size_request (entry8n, 196, 42);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8n), 8226);

  entry9n = gtk_entry_new ();
  gtk_widget_show (entry9n);
  gtk_fixed_put (GTK_FIXED (fixed17), entry9n, 136, 88);
  gtk_widget_set_size_request (entry9n, 200, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9n), 8226);

  entry7005 = gtk_entry_new ();
  gtk_widget_show (entry7005);
  gtk_fixed_put (GTK_FIXED (fixed17), entry7005, 136, 192);
  gtk_widget_set_size_request (entry7005, 200, 34);
  gtk_entry_set_text (GTK_ENTRY (entry7005), _("A"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7005), 8226);

  label97 = gtk_label_new (_("login:"));
  gtk_widget_show (label97);
  gtk_fixed_put (GTK_FIXED (fixed17), label97, 48, 40);
  gtk_widget_set_size_request (label97, 49, 17);

  label98 = gtk_label_new (_("password:"));
  gtk_widget_show (label98);
  gtk_fixed_put (GTK_FIXED (fixed17), label98, 48, 96);
  gtk_widget_set_size_request (label98, 49, 17);

  label99 = gtk_label_new (_("role:"));
  gtk_widget_show (label99);
  gtk_fixed_put (GTK_FIXED (fixed17), label99, 48, 152);
  gtk_widget_set_size_request (label99, 49, 17);

  combobox2n = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2n);
  gtk_fixed_put (GTK_FIXED (fixed17), combobox2n, 140, 150);
  gtk_widget_set_size_request (combobox2n, 200, 33);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2n), _("medecin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2n), _("coach"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2n), _("kine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2n), _("dieteticien"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2n), _("adherent"));

  button8n = gtk_button_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (button8n);
  gtk_fixed_put (GTK_FIXED (fixed17), button8n, 200, 248);
  gtk_widget_set_size_request (button8n, 78, 33);

  label100 = gtk_label_new (_("id:"));
  gtk_widget_show (label100);
  gtk_fixed_put (GTK_FIXED (fixed17), label100, 48, 208);
  gtk_widget_set_size_request (label100, 57, 17);

  label28n = gtk_label_new ("");
  gtk_widget_show (label28n);
  gtk_fixed_put (GTK_FIXED (fixed17), label28n, 352, 40);
  gtk_widget_set_size_request (label28n, 57, 17);

  label29n = gtk_label_new ("");
  gtk_widget_show (label29n);
  gtk_fixed_put (GTK_FIXED (fixed17), label29n, 344, 88);
  gtk_widget_set_size_request (label29n, 57, 17);

  label30n = gtk_label_new ("");
  gtk_widget_show (label30n);
  gtk_fixed_put (GTK_FIXED (fixed17), label30n, 352, 208);
  gtk_widget_set_size_request (label30n, 57, 17);

  fixed18 = gtk_fixed_new ();
  gtk_widget_show (fixed18);
  gtk_fixed_put (GTK_FIXED (fixed17), fixed18, 0, 0);
  gtk_widget_set_size_request (fixed18, 0, 0);

  entry7006 = gtk_entry_new ();
  gtk_widget_show (entry7006);
  gtk_fixed_put (GTK_FIXED (fixed18), entry7006, 136, 24);
  gtk_widget_set_size_request (entry7006, 196, 42);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7006), 8226);

  entry7007 = gtk_entry_new ();
  gtk_widget_show (entry7007);
  gtk_fixed_put (GTK_FIXED (fixed18), entry7007, 136, 88);
  gtk_widget_set_size_request (entry7007, 200, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7007), 8226);

  entry7008 = gtk_entry_new ();
  gtk_widget_show (entry7008);
  gtk_fixed_put (GTK_FIXED (fixed18), entry7008, 136, 192);
  gtk_widget_set_size_request (entry7008, 200, 34);
  gtk_entry_set_text (GTK_ENTRY (entry7008), _("A"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7008), 8226);

  label104 = gtk_label_new (_("login:"));
  gtk_widget_show (label104);
  gtk_fixed_put (GTK_FIXED (fixed18), label104, 48, 40);
  gtk_widget_set_size_request (label104, 49, 17);

  label105 = gtk_label_new (_("password:"));
  gtk_widget_show (label105);
  gtk_fixed_put (GTK_FIXED (fixed18), label105, 48, 96);
  gtk_widget_set_size_request (label105, 49, 17);

  label106 = gtk_label_new (_("role:"));
  gtk_widget_show (label106);
  gtk_fixed_put (GTK_FIXED (fixed18), label106, 48, 152);
  gtk_widget_set_size_request (label106, 49, 17);

  combobox4001 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox4001);
  gtk_fixed_put (GTK_FIXED (fixed18), combobox4001, 140, 150);
  gtk_widget_set_size_request (combobox4001, 200, 33);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4001), _("medecin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4001), _("coach"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4001), _("kine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4001), _("dieteticien"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4001), _("adherent"));

  button18 = gtk_button_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (button18);
  gtk_fixed_put (GTK_FIXED (fixed18), button18, 200, 248);
  gtk_widget_set_size_request (button18, 78, 33);

  label107 = gtk_label_new (_("id:"));
  gtk_widget_show (label107);
  gtk_fixed_put (GTK_FIXED (fixed18), label107, 48, 208);
  gtk_widget_set_size_request (label107, 57, 17);

  label108 = gtk_label_new ("");
  gtk_widget_show (label108);
  gtk_fixed_put (GTK_FIXED (fixed18), label108, 352, 40);
  gtk_widget_set_size_request (label108, 57, 17);

  label109 = gtk_label_new ("");
  gtk_widget_show (label109);
  gtk_fixed_put (GTK_FIXED (fixed18), label109, 344, 88);
  gtk_widget_set_size_request (label109, 57, 17);

  label110 = gtk_label_new (_("label103"));
  gtk_widget_show (label110);
  gtk_fixed_put (GTK_FIXED (fixed18), label110, 0, 0);
  gtk_widget_set_size_request (label110, 57, 17);

  label31n = gtk_label_new ("");
  gtk_widget_show (label31n);
  gtk_fixed_put (GTK_FIXED (fixed17), label31n, 24, 296);
  gtk_widget_set_size_request (label31n, 400, 24);

  g_signal_connect ((gpointer) button8n, "clicked",
                    G_CALLBACK (on_button8n_clicked),
                    NULL);
  g_signal_connect ((gpointer) button18, "clicked",
                    G_CALLBACK (on_button8n_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (AjouterCompte, AjouterCompte, "AjouterCompte");
  GLADE_HOOKUP_OBJECT (AjouterCompte, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (AjouterCompte, entry8n, "entry8n");
  GLADE_HOOKUP_OBJECT (AjouterCompte, entry9n, "entry9n");
  GLADE_HOOKUP_OBJECT (AjouterCompte, entry7005, "entry7005");
  GLADE_HOOKUP_OBJECT (AjouterCompte, label97, "label97");
  GLADE_HOOKUP_OBJECT (AjouterCompte, label98, "label98");
  GLADE_HOOKUP_OBJECT (AjouterCompte, label99, "label99");
  GLADE_HOOKUP_OBJECT (AjouterCompte, combobox2n, "combobox2n");
  GLADE_HOOKUP_OBJECT (AjouterCompte, button8n, "button8n");
  GLADE_HOOKUP_OBJECT (AjouterCompte, label100, "label100");
  GLADE_HOOKUP_OBJECT (AjouterCompte, label28n, "label28n");
  GLADE_HOOKUP_OBJECT (AjouterCompte, label29n, "label29n");
  GLADE_HOOKUP_OBJECT (AjouterCompte, label30n, "label30n");
  GLADE_HOOKUP_OBJECT (AjouterCompte, fixed18, "fixed18");
  GLADE_HOOKUP_OBJECT (AjouterCompte, entry7006, "entry7006");
  GLADE_HOOKUP_OBJECT (AjouterCompte, entry7007, "entry7007");
  GLADE_HOOKUP_OBJECT (AjouterCompte, entry7008, "entry7008");
  GLADE_HOOKUP_OBJECT (AjouterCompte, label104, "label104");
  GLADE_HOOKUP_OBJECT (AjouterCompte, label105, "label105");
  GLADE_HOOKUP_OBJECT (AjouterCompte, label106, "label106");
  GLADE_HOOKUP_OBJECT (AjouterCompte, combobox4001, "combobox4001");
  GLADE_HOOKUP_OBJECT (AjouterCompte, button18, "button18");
  GLADE_HOOKUP_OBJECT (AjouterCompte, label107, "label107");
  GLADE_HOOKUP_OBJECT (AjouterCompte, label108, "label108");
  GLADE_HOOKUP_OBJECT (AjouterCompte, label109, "label109");
  GLADE_HOOKUP_OBJECT (AjouterCompte, label110, "label110");
  GLADE_HOOKUP_OBJECT (AjouterCompte, label31n, "label31n");

  return AjouterCompte;
}

GtkWidget*
create_annulation (void)
{
  GtkWidget *annulation;
  GtkWidget *fixed19;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkWidget *label119;
  GtkWidget *label118;
  GtkWidget *image19;
  GtkWidget *button192;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image17;
  GtkWidget *label120;
  GtkWidget *button193;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image18;
  GtkWidget *label121;

  annulation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (annulation, 490, 490);
  gtk_window_set_title (GTK_WINDOW (annulation), _("annulation rendez vous"));

  fixed19 = gtk_fixed_new ();
  gtk_widget_show (fixed19);
  gtk_container_add (GTK_CONTAINER (annulation), fixed19);

  spinbutton4_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed19), spinbutton4, 200, 240);
  gtk_widget_set_size_request (spinbutton4, 70, 34);

  label119 = gtk_label_new (_("(d'apres la liste afficher)"));
  gtk_widget_show (label119);
  gtk_fixed_put (GTK_FIXED (fixed19), label119, 152, 152);
  gtk_widget_set_size_request (label119, 185, 25);

  label118 = gtk_label_new (_("choisir l'idd du rendez vous \303\240 annuler"));
  gtk_widget_show (label118);
  gtk_fixed_put (GTK_FIXED (fixed19), label118, 120, 120);
  gtk_widget_set_size_request (label118, 256, 24);

  image19 = create_pixmap (annulation, "outlook.png");
  gtk_widget_show (image19);
  gtk_fixed_put (GTK_FIXED (fixed19), image19, 0, 0);
  gtk_widget_set_size_request (image19, 490, 490);

  button192 = gtk_button_new ();
  gtk_widget_show (button192);
  gtk_fixed_put (GTK_FIXED (fixed19), button192, 120, 328);
  gtk_widget_set_size_request (button192, 86, 33);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button192), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image17 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox12), image17, FALSE, FALSE, 0);

  label120 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label120);
  gtk_box_pack_start (GTK_BOX (hbox12), label120, FALSE, FALSE, 0);

  button193 = gtk_button_new ();
  gtk_widget_show (button193);
  gtk_fixed_put (GTK_FIXED (fixed19), button193, 288, 328);
  gtk_widget_set_size_request (button193, 86, 33);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button193), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image18 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox13), image18, FALSE, FALSE, 0);

  label121 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label121);
  gtk_box_pack_start (GTK_BOX (hbox13), label121, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button192, "clicked",
                    G_CALLBACK (on_button192_clicked),
                    NULL);
  g_signal_connect ((gpointer) button193, "clicked",
                    G_CALLBACK (on_button193_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (annulation, annulation, "annulation");
  GLADE_HOOKUP_OBJECT (annulation, fixed19, "fixed19");
  GLADE_HOOKUP_OBJECT (annulation, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (annulation, label119, "label119");
  GLADE_HOOKUP_OBJECT (annulation, label118, "label118");
  GLADE_HOOKUP_OBJECT (annulation, image19, "image19");
  GLADE_HOOKUP_OBJECT (annulation, button192, "button192");
  GLADE_HOOKUP_OBJECT (annulation, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (annulation, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (annulation, image17, "image17");
  GLADE_HOOKUP_OBJECT (annulation, label120, "label120");
  GLADE_HOOKUP_OBJECT (annulation, button193, "button193");
  GLADE_HOOKUP_OBJECT (annulation, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (annulation, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (annulation, image18, "image18");
  GLADE_HOOKUP_OBJECT (annulation, label121, "label121");

  return annulation;
}

