/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_login (void)
{
  GtkWidget *login;
  GtkWidget *fixed1;
  GtkWidget *entry1n;
  GtkWidget *entry2n;
  GtkWidget *label2n;
  GtkWidget *button1n;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label3n;
  GtkWidget *label4n;
  GtkWidget *label1n;
  GtkWidget *button27n;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label54;

  login = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (login), _("login"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (login), fixed1);

  entry1n = gtk_entry_new ();
  gtk_widget_show (entry1n);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1n, 128, 40);
  gtk_widget_set_size_request (entry1n, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1n), 8226);

  entry2n = gtk_entry_new ();
  gtk_widget_show (entry2n);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2n, 128, 112);
  gtk_widget_set_size_request (entry2n, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entry2n), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2n), 8226);

  label2n = gtk_label_new (_("password:"));
  gtk_widget_show (label2n);
  gtk_fixed_put (GTK_FIXED (fixed1), label2n, 16, 120);
  gtk_widget_set_size_request (label2n, 120, 17);

  button1n = gtk_button_new ();
  gtk_widget_show (button1n);
  gtk_fixed_put (GTK_FIXED (fixed1), button1n, 136, 168);
  gtk_widget_set_size_request (button1n, 144, 37);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1n), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label3n = gtk_label_new_with_mnemonic (_("enrter"));
  gtk_widget_show (label3n);
  gtk_box_pack_start (GTK_BOX (hbox1), label3n, FALSE, FALSE, 0);

  label4n = gtk_label_new ("");
  gtk_widget_show (label4n);
  gtk_fixed_put (GTK_FIXED (fixed1), label4n, 104, 216);
  gtk_widget_set_size_request (label4n, 232, 49);

  label1n = gtk_label_new (_("login:"));
  gtk_widget_show (label1n);
  gtk_fixed_put (GTK_FIXED (fixed1), label1n, 72, 40);
  gtk_widget_set_size_request (label1n, 41, 17);

  button27n = gtk_button_new ();
  gtk_widget_show (button27n);
  gtk_fixed_put (GTK_FIXED (fixed1), button27n, 72, 232);
  gtk_widget_set_size_request (button27n, 68, 29);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (button27n), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label54 = gtk_label_new_with_mnemonic (_("quitter"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox22), label54, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button1n, "clicked",
                    G_CALLBACK (on_button1n_clicked),
                    NULL);
  g_signal_connect ((gpointer) button27n, "clicked",
                    G_CALLBACK (on_button27n_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (login, login, "login");
  GLADE_HOOKUP_OBJECT (login, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (login, entry1n, "entry1n");
  GLADE_HOOKUP_OBJECT (login, entry2n, "entry2n");
  GLADE_HOOKUP_OBJECT (login, label2n, "label2n");
  GLADE_HOOKUP_OBJECT (login, button1n, "button1n");
  GLADE_HOOKUP_OBJECT (login, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (login, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (login, image1, "image1");
  GLADE_HOOKUP_OBJECT (login, label3n, "label3n");
  GLADE_HOOKUP_OBJECT (login, label4n, "label4n");
  GLADE_HOOKUP_OBJECT (login, label1n, "label1n");
  GLADE_HOOKUP_OBJECT (login, button27n, "button27n");
  GLADE_HOOKUP_OBJECT (login, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (login, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (login, image22, "image22");
  GLADE_HOOKUP_OBJECT (login, label54, "label54");

  return login;
}

GtkWidget*
create_Admin (void)
{
  GtkWidget *Admin;
  GtkWidget *fixed2;
  GtkWidget *button2n_;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label11n;
  GtkWidget *label5n;
  GtkWidget *button6n;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label23n;
  GtkWidget *button9n;
  GtkWidget *button25n;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label52;
  GtkWidget *button26n;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *label53;

  Admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Admin), _("Admin"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Admin), fixed2);

  button2n_ = gtk_button_new ();
  gtk_widget_show (button2n_);
  gtk_fixed_put (GTK_FIXED (fixed2), button2n_, 120, 80);
  gtk_widget_set_size_request (button2n_, 136, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2n_), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label11n = gtk_label_new_with_mnemonic (_("ProfilAdmin"));
  gtk_widget_show (label11n);
  gtk_box_pack_start (GTK_BOX (hbox2), label11n, FALSE, FALSE, 0);

  label5n = gtk_label_new (_("bienvenu dans l 'espace admin"));
  gtk_widget_show (label5n);
  gtk_fixed_put (GTK_FIXED (fixed2), label5n, 24, 16);
  gtk_widget_set_size_request (label5n, 312, 48);

  button6n = gtk_button_new ();
  gtk_widget_show (button6n);
  gtk_fixed_put (GTK_FIXED (fixed2), button6n, 104, 128);
  gtk_widget_set_size_request (button6n, 168, 37);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button6n), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label23n = gtk_label_new_with_mnemonic (_("GestionCompte"));
  gtk_widget_show (label23n);
  gtk_box_pack_start (GTK_BOX (hbox6), label23n, FALSE, FALSE, 0);

  button9n = gtk_button_new_with_mnemonic (_("GestionEvent"));
  gtk_widget_show (button9n);
  gtk_fixed_put (GTK_FIXED (fixed2), button9n, 120, 184);
  gtk_widget_set_size_request (button9n, 136, 45);

  button25n = gtk_button_new ();
  gtk_widget_show (button25n);
  gtk_fixed_put (GTK_FIXED (fixed2), button25n, 392, 64);
  gtk_widget_set_size_request (button25n, 68, 29);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button25n), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label52 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox20), label52, FALSE, FALSE, 0);

  button26n = gtk_button_new ();
  gtk_widget_show (button26n);
  gtk_fixed_put (GTK_FIXED (fixed2), button26n, 408, 152);
  gtk_widget_set_size_request (button26n, 68, 29);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (button26n), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  label53 = gtk_label_new_with_mnemonic (_("quitter"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox21), label53, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button2n_, "clicked",
                    G_CALLBACK (on_button2n__clicked),
                    NULL);
  g_signal_connect ((gpointer) button6n, "clicked",
                    G_CALLBACK (on_button6n_clicked),
                    NULL);
  g_signal_connect ((gpointer) button9n, "clicked",
                    G_CALLBACK (on_button9n_clicked),
                    NULL);
  g_signal_connect ((gpointer) button25n, "clicked",
                    G_CALLBACK (on_button25n_clicked),
                    NULL);
  g_signal_connect ((gpointer) button26n, "clicked",
                    G_CALLBACK (on_button26n_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Admin, Admin, "Admin");
  GLADE_HOOKUP_OBJECT (Admin, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Admin, button2n_, "button2n_");
  GLADE_HOOKUP_OBJECT (Admin, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Admin, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Admin, image2, "image2");
  GLADE_HOOKUP_OBJECT (Admin, label11n, "label11n");
  GLADE_HOOKUP_OBJECT (Admin, label5n, "label5n");
  GLADE_HOOKUP_OBJECT (Admin, button6n, "button6n");
  GLADE_HOOKUP_OBJECT (Admin, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Admin, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Admin, image6, "image6");
  GLADE_HOOKUP_OBJECT (Admin, label23n, "label23n");
  GLADE_HOOKUP_OBJECT (Admin, button9n, "button9n");
  GLADE_HOOKUP_OBJECT (Admin, button25n, "button25n");
  GLADE_HOOKUP_OBJECT (Admin, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (Admin, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (Admin, image20, "image20");
  GLADE_HOOKUP_OBJECT (Admin, label52, "label52");
  GLADE_HOOKUP_OBJECT (Admin, button26n, "button26n");
  GLADE_HOOKUP_OBJECT (Admin, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (Admin, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (Admin, image21, "image21");
  GLADE_HOOKUP_OBJECT (Admin, label53, "label53");

  return Admin;
}

GtkWidget*
create_coach (void)
{
  GtkWidget *coach;
  GtkWidget *fixed3;
  GtkWidget *label6n;

  coach = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (coach), _("coach"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (coach), fixed3);

  label6n = gtk_label_new (_("bienvenu dans l' espace coach"));
  gtk_widget_show (label6n);
  gtk_fixed_put (GTK_FIXED (fixed3), label6n, 168, 64);
  gtk_widget_set_size_request (label6n, 224, 57);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (coach, coach, "coach");
  GLADE_HOOKUP_OBJECT (coach, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (coach, label6n, "label6n");

  return coach;
}

GtkWidget*
create_adherent (void)
{
  GtkWidget *adherent;
  GtkWidget *fixed4;
  GtkWidget *label7n;

  adherent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (adherent), _("adherent"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (adherent), fixed4);

  label7n = gtk_label_new (_("binevenu dans l'espace adh\303\251rent"));
  gtk_widget_show (label7n);
  gtk_fixed_put (GTK_FIXED (fixed4), label7n, 56, 64);
  gtk_widget_set_size_request (label7n, 320, 65);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (adherent, adherent, "adherent");
  GLADE_HOOKUP_OBJECT (adherent, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (adherent, label7n, "label7n");

  return adherent;
}

GtkWidget*
create_medecin (void)
{
  GtkWidget *medecin;
  GtkWidget *fixed5;
  GtkWidget *label8n;

  medecin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (medecin), _("medecin"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (medecin), fixed5);

  label8n = gtk_label_new (_("bienvenu dans l'espace m\303\251d\303\251cin"));
  gtk_widget_show (label8n);
  gtk_fixed_put (GTK_FIXED (fixed5), label8n, 72, 32);
  gtk_widget_set_size_request (label8n, 272, 73);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (medecin, medecin, "medecin");
  GLADE_HOOKUP_OBJECT (medecin, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (medecin, label8n, "label8n");

  return medecin;
}

GtkWidget*
create_kinesitherapeute (void)
{
  GtkWidget *kinesitherapeute;
  GtkWidget *fixed6;
  GtkWidget *label9n;

  kinesitherapeute = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (kinesitherapeute), _("kinesitherapeute"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (kinesitherapeute), fixed6);

  label9n = gtk_label_new (_("bienvenu dans l'espace kin\303\251sith\303\251rapeute"));
  gtk_widget_show (label9n);
  gtk_fixed_put (GTK_FIXED (fixed6), label9n, 48, 24);
  gtk_widget_set_size_request (label9n, 328, 57);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (kinesitherapeute, kinesitherapeute, "kinesitherapeute");
  GLADE_HOOKUP_OBJECT (kinesitherapeute, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (kinesitherapeute, label9n, "label9n");

  return kinesitherapeute;
}

GtkWidget*
create_dieteticien (void)
{
  GtkWidget *dieteticien;
  GtkWidget *fixed7;
  GtkWidget *label10n;

  dieteticien = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (dieteticien), _("dieteticien"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (dieteticien), fixed7);

  label10n = gtk_label_new (_("bienvenu dans l 'espace di\303\251t\303\251ticien"));
  gtk_widget_show (label10n);
  gtk_fixed_put (GTK_FIXED (fixed7), label10n, 40, 32);
  gtk_widget_set_size_request (label10n, 256, 81);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dieteticien, dieteticien, "dieteticien");
  GLADE_HOOKUP_OBJECT (dieteticien, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (dieteticien, label10n, "label10n");

  return dieteticien;
}

GtkWidget*
create_ProfilAdmin (void)
{
  GtkWidget *ProfilAdmin;
  GtkWidget *fixed8;
  GtkWidget *label14n;
  GtkWidget *label15n;
  GtkWidget *entry3n;
  GtkWidget *entry4n;
  GtkWidget *entry5n;
  GtkWidget *entry6n;
  GtkWidget *entry7n;
  GtkWidget *label18n;
  GtkWidget *label17n;
  GtkWidget *label16n;
  GtkWidget *label12n;
  GtkWidget *label13n;
  GtkObject *spinbutton1n_adj;
  GtkWidget *spinbutton1n;
  GtkWidget *combobox1n;
  GtkWidget *button5n;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label21n;
  GtkWidget *button4n;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label20n;
  GtkWidget *button3n;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label19n;

  ProfilAdmin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ProfilAdmin), _("ProfilAdmin"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (ProfilAdmin), fixed8);

  label14n = gtk_label_new (_("age:"));
  gtk_widget_show (label14n);
  gtk_fixed_put (GTK_FIXED (fixed8), label14n, 48, 80);
  gtk_widget_set_size_request (label14n, 41, 17);

  label15n = gtk_label_new (_("sexe:"));
  gtk_widget_show (label15n);
  gtk_fixed_put (GTK_FIXED (fixed8), label15n, 56, 112);
  gtk_widget_set_size_request (label15n, 41, 17);

  entry3n = gtk_entry_new ();
  gtk_widget_show (entry3n);
  gtk_fixed_put (GTK_FIXED (fixed8), entry3n, 128, 8);
  gtk_widget_set_size_request (entry3n, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3n), 8226);

  entry4n = gtk_entry_new ();
  gtk_widget_show (entry4n);
  gtk_fixed_put (GTK_FIXED (fixed8), entry4n, 128, 40);
  gtk_widget_set_size_request (entry4n, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4n), 8226);

  entry5n = gtk_entry_new ();
  gtk_widget_show (entry5n);
  gtk_fixed_put (GTK_FIXED (fixed8), entry5n, 136, 152);
  gtk_widget_set_size_request (entry5n, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5n), 8226);

  entry6n = gtk_entry_new ();
  gtk_widget_show (entry6n);
  gtk_fixed_put (GTK_FIXED (fixed8), entry6n, 136, 184);
  gtk_widget_set_size_request (entry6n, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6n), 8226);

  entry7n = gtk_entry_new ();
  gtk_widget_show (entry7n);
  gtk_fixed_put (GTK_FIXED (fixed8), entry7n, 136, 216);
  gtk_widget_set_size_request (entry7n, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7n), 8226);

  label18n = gtk_label_new (_("mail:"));
  gtk_widget_show (label18n);
  gtk_fixed_put (GTK_FIXED (fixed8), label18n, 64, 224);
  gtk_widget_set_size_request (label18n, 41, 17);

  label17n = gtk_label_new (_("adress:"));
  gtk_widget_show (label17n);
  gtk_fixed_put (GTK_FIXED (fixed8), label17n, 48, 192);
  gtk_widget_set_size_request (label17n, 72, 17);

  label16n = gtk_label_new (_("N \302\260 tel:"));
  gtk_widget_show (label16n);
  gtk_fixed_put (GTK_FIXED (fixed8), label16n, 64, 152);
  gtk_widget_set_size_request (label16n, 41, 17);

  label12n = gtk_label_new (_("nom:"));
  gtk_widget_show (label12n);
  gtk_fixed_put (GTK_FIXED (fixed8), label12n, 32, 16);
  gtk_widget_set_size_request (label12n, 80, 17);

  label13n = gtk_label_new (_("prenom:"));
  gtk_widget_show (label13n);
  gtk_fixed_put (GTK_FIXED (fixed8), label13n, 24, 48);
  gtk_widget_set_size_request (label13n, 96, 17);

  spinbutton1n_adj = gtk_adjustment_new (1, 1, 90, 1, 10, 10);
  spinbutton1n = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1n_adj), 1, 0);
  gtk_widget_show (spinbutton1n);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton1n, 144, 72);
  gtk_widget_set_size_request (spinbutton1n, 60, 27);

  combobox1n = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1n);
  gtk_fixed_put (GTK_FIXED (fixed8), combobox1n, 136, 112);
  gtk_widget_set_size_request (combobox1n, 159, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1n), _("homme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1n), _("femme"));

  button5n = gtk_button_new ();
  gtk_widget_show (button5n);
  gtk_fixed_put (GTK_FIXED (fixed8), button5n, 336, 288);
  gtk_widget_set_size_request (button5n, 104, 29);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button5n), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label21n = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label21n);
  gtk_box_pack_start (GTK_BOX (hbox5), label21n, FALSE, FALSE, 0);

  button4n = gtk_button_new ();
  gtk_widget_show (button4n);
  gtk_fixed_put (GTK_FIXED (fixed8), button4n, 160, 288);
  gtk_widget_set_size_request (button4n, 144, 29);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button4n), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label20n = gtk_label_new_with_mnemonic (_("mise a jour"));
  gtk_widget_show (label20n);
  gtk_box_pack_start (GTK_BOX (hbox4), label20n, FALSE, FALSE, 0);

  button3n = gtk_button_new ();
  gtk_widget_show (button3n);
  gtk_fixed_put (GTK_FIXED (fixed8), button3n, 32, 288);
  gtk_widget_set_size_request (button3n, 96, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3n), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label19n = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label19n);
  gtk_box_pack_start (GTK_BOX (hbox3), label19n, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button5n, "clicked",
                    G_CALLBACK (on_button5n_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4n, "clicked",
                    G_CALLBACK (on_button4n_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3n, "clicked",
                    G_CALLBACK (on_button3n_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ProfilAdmin, ProfilAdmin, "ProfilAdmin");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, label14n, "label14n");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, label15n, "label15n");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, entry3n, "entry3n");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, entry4n, "entry4n");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, entry5n, "entry5n");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, entry6n, "entry6n");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, entry7n, "entry7n");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, label18n, "label18n");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, label17n, "label17n");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, label16n, "label16n");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, label12n, "label12n");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, label13n, "label13n");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, spinbutton1n, "spinbutton1n");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, combobox1n, "combobox1n");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, button5n, "button5n");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, image5, "image5");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, label21n, "label21n");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, button4n, "button4n");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, image4, "image4");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, label20n, "label20n");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, button3n, "button3n");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, image3, "image3");
  GLADE_HOOKUP_OBJECT (ProfilAdmin, label19n, "label19n");

  return ProfilAdmin;
}

GtkWidget*
create_GestionCompte (void)
{
  GtkWidget *GestionCompte;
  GtkWidget *fixed9;
  GtkWidget *scrolledwindow1n;
  GtkWidget *treeview1n;
  GtkWidget *button7n;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label22n;
  GtkWidget *button16n;
  GtkWidget *button21n;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label48;
  GtkWidget *button22n;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label49;

  GestionCompte = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (GestionCompte), _("GestionCompte"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (GestionCompte), fixed9);

  scrolledwindow1n = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1n);
  gtk_fixed_put (GTK_FIXED (fixed9), scrolledwindow1n, 52, 50);
  gtk_widget_set_size_request (scrolledwindow1n, 400, 229);

  treeview1n = gtk_tree_view_new ();
  gtk_widget_show (treeview1n);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1n), treeview1n);

  button7n = gtk_button_new ();
  gtk_widget_show (button7n);
  gtk_fixed_put (GTK_FIXED (fixed9), button7n, 552, 56);
  gtk_widget_set_size_request (button7n, 168, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button7n), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label22n = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label22n);
  gtk_box_pack_start (GTK_BOX (hbox7), label22n, FALSE, FALSE, 0);

  button16n = gtk_button_new_with_mnemonic (_("afficher les profil"));
  gtk_widget_show (button16n);
  gtk_fixed_put (GTK_FIXED (fixed9), button16n, 552, 128);
  gtk_widget_set_size_request (button16n, 176, 37);

  button21n = gtk_button_new ();
  gtk_widget_show (button21n);
  gtk_fixed_put (GTK_FIXED (fixed9), button21n, 608, 200);
  gtk_widget_set_size_request (button21n, 104, 29);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button21n), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox16), label48, FALSE, FALSE, 0);

  button22n = gtk_button_new ();
  gtk_widget_show (button22n);
  gtk_fixed_put (GTK_FIXED (fixed9), button22n, 632, 240);
  gtk_widget_set_size_request (button22n, 68, 29);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button22n), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("quitter"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox17), label49, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1n, "row_activated",
                    G_CALLBACK (on_treeview1n_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button7n, "clicked",
                    G_CALLBACK (on_button7n_clicked),
                    NULL);
  g_signal_connect ((gpointer) button16n, "clicked",
                    G_CALLBACK (on_button16n_clicked),
                    NULL);
  g_signal_connect ((gpointer) button21n, "clicked",
                    G_CALLBACK (on_button21n_clicked),
                    NULL);
  g_signal_connect ((gpointer) button22n, "clicked",
                    G_CALLBACK (on_button22n_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GestionCompte, GestionCompte, "GestionCompte");
  GLADE_HOOKUP_OBJECT (GestionCompte, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (GestionCompte, scrolledwindow1n, "scrolledwindow1n");
  GLADE_HOOKUP_OBJECT (GestionCompte, treeview1n, "treeview1n");
  GLADE_HOOKUP_OBJECT (GestionCompte, button7n, "button7n");
  GLADE_HOOKUP_OBJECT (GestionCompte, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (GestionCompte, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (GestionCompte, image7, "image7");
  GLADE_HOOKUP_OBJECT (GestionCompte, label22n, "label22n");
  GLADE_HOOKUP_OBJECT (GestionCompte, button16n, "button16n");
  GLADE_HOOKUP_OBJECT (GestionCompte, button21n, "button21n");
  GLADE_HOOKUP_OBJECT (GestionCompte, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (GestionCompte, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (GestionCompte, image16, "image16");
  GLADE_HOOKUP_OBJECT (GestionCompte, label48, "label48");
  GLADE_HOOKUP_OBJECT (GestionCompte, button22n, "button22n");
  GLADE_HOOKUP_OBJECT (GestionCompte, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (GestionCompte, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (GestionCompte, image17, "image17");
  GLADE_HOOKUP_OBJECT (GestionCompte, label49, "label49");

  return GestionCompte;
}

GtkWidget*
create_AjouterCompte (void)
{
  GtkWidget *AjouterCompte;
  GtkWidget *fixed10;
  GtkWidget *entry8n;
  GtkWidget *entry9n;
  GtkWidget *entry10n;
  GtkWidget *label25n;
  GtkWidget *label26n;
  GtkWidget *label27n;
  GtkWidget *combobox2n;
  GtkWidget *button8n;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label277n;
  GtkWidget *label28n;
  GtkWidget *label29n;
  GtkWidget *label30n;
  GtkWidget *label31n;
  GtkWidget *label24n;

  AjouterCompte = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (AjouterCompte), _("AjouterCompte"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (AjouterCompte), fixed10);

  entry8n = gtk_entry_new ();
  gtk_widget_show (entry8n);
  gtk_fixed_put (GTK_FIXED (fixed10), entry8n, 176, 32);
  gtk_widget_set_size_request (entry8n, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8n), 8226);

  entry9n = gtk_entry_new ();
  gtk_widget_show (entry9n);
  gtk_fixed_put (GTK_FIXED (fixed10), entry9n, 176, 80);
  gtk_widget_set_size_request (entry9n, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9n), 8226);

  entry10n = gtk_entry_new ();
  gtk_widget_show (entry10n);
  gtk_fixed_put (GTK_FIXED (fixed10), entry10n, 176, 168);
  gtk_widget_set_size_request (entry10n, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10n), 8226);

  label25n = gtk_label_new (_("password:"));
  gtk_widget_show (label25n);
  gtk_fixed_put (GTK_FIXED (fixed10), label25n, 56, 88);
  gtk_widget_set_size_request (label25n, 112, 17);

  label26n = gtk_label_new (_("role:"));
  gtk_widget_show (label26n);
  gtk_fixed_put (GTK_FIXED (fixed10), label26n, 80, 128);
  gtk_widget_set_size_request (label26n, 65, 25);

  label27n = gtk_label_new (_("cin:"));
  gtk_widget_show (label27n);
  gtk_fixed_put (GTK_FIXED (fixed10), label27n, 72, 168);
  gtk_widget_set_size_request (label27n, 80, 25);

  combobox2n = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2n);
  gtk_fixed_put (GTK_FIXED (fixed10), combobox2n, 176, 128);
  gtk_widget_set_size_request (combobox2n, 160, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2n), _("m\303\251decin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2n), _("coach"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2n), _("kin\303\251sith\303\251rapeute"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2n), _("di\303\251t\303\251ticien"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2n), _("adh\303\251rent"));

  button8n = gtk_button_new ();
  gtk_widget_show (button8n);
  gtk_fixed_put (GTK_FIXED (fixed10), button8n, 184, 216);
  gtk_widget_set_size_request (button8n, 112, 37);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button8n), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label277n = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label277n);
  gtk_box_pack_start (GTK_BOX (hbox8), label277n, FALSE, FALSE, 0);

  label28n = gtk_label_new ("");
  gtk_widget_show (label28n);
  gtk_fixed_put (GTK_FIXED (fixed10), label28n, 344, 40);
  gtk_widget_set_size_request (label28n, 41, 17);

  label29n = gtk_label_new ("");
  gtk_widget_show (label29n);
  gtk_fixed_put (GTK_FIXED (fixed10), label29n, 352, 80);
  gtk_widget_set_size_request (label29n, 41, 17);

  label30n = gtk_label_new ("");
  gtk_widget_show (label30n);
  gtk_fixed_put (GTK_FIXED (fixed10), label30n, 360, 168);
  gtk_widget_set_size_request (label30n, 49, 17);

  label31n = gtk_label_new ("");
  gtk_widget_show (label31n);
  gtk_fixed_put (GTK_FIXED (fixed10), label31n, 64, 280);
  gtk_widget_set_size_request (label31n, 320, 33);

  label24n = gtk_label_new (_("login:"));
  gtk_widget_show (label24n);
  gtk_fixed_put (GTK_FIXED (fixed10), label24n, 80, 40);
  gtk_widget_set_size_request (label24n, 41, 17);

  g_signal_connect ((gpointer) button8n, "clicked",
                    G_CALLBACK (on_button8n_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (AjouterCompte, AjouterCompte, "AjouterCompte");
  GLADE_HOOKUP_OBJECT (AjouterCompte, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (AjouterCompte, entry8n, "entry8n");
  GLADE_HOOKUP_OBJECT (AjouterCompte, entry9n, "entry9n");
  GLADE_HOOKUP_OBJECT (AjouterCompte, entry10n, "entry10n");
  GLADE_HOOKUP_OBJECT (AjouterCompte, label25n, "label25n");
  GLADE_HOOKUP_OBJECT (AjouterCompte, label26n, "label26n");
  GLADE_HOOKUP_OBJECT (AjouterCompte, label27n, "label27n");
  GLADE_HOOKUP_OBJECT (AjouterCompte, combobox2n, "combobox2n");
  GLADE_HOOKUP_OBJECT (AjouterCompte, button8n, "button8n");
  GLADE_HOOKUP_OBJECT (AjouterCompte, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (AjouterCompte, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (AjouterCompte, image8, "image8");
  GLADE_HOOKUP_OBJECT (AjouterCompte, label277n, "label277n");
  GLADE_HOOKUP_OBJECT (AjouterCompte, label28n, "label28n");
  GLADE_HOOKUP_OBJECT (AjouterCompte, label29n, "label29n");
  GLADE_HOOKUP_OBJECT (AjouterCompte, label30n, "label30n");
  GLADE_HOOKUP_OBJECT (AjouterCompte, label31n, "label31n");
  GLADE_HOOKUP_OBJECT (AjouterCompte, label24n, "label24n");

  return AjouterCompte;
}

GtkWidget*
create_GestionEvent (void)
{
  GtkWidget *GestionEvent;
  GtkWidget *fixed11;
  GtkWidget *scrolledwindow2n;
  GtkWidget *treeview2n;
  GtkWidget *button10n;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label1;
  GtkWidget *button23n;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label50;
  GtkWidget *button24n;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label51;

  GestionEvent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (GestionEvent), _("GestionEvent"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (GestionEvent), fixed11);

  scrolledwindow2n = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2n);
  gtk_fixed_put (GTK_FIXED (fixed11), scrolledwindow2n, 40, 48);
  gtk_widget_set_size_request (scrolledwindow2n, 297, 223);

  treeview2n = gtk_tree_view_new ();
  gtk_widget_show (treeview2n);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2n), treeview2n);

  button10n = gtk_button_new ();
  gtk_widget_show (button10n);
  gtk_fixed_put (GTK_FIXED (fixed11), button10n, 360, 64);
  gtk_widget_set_size_request (button10n, 136, 37);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button10n), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox9), label1, FALSE, FALSE, 0);

  button23n = gtk_button_new ();
  gtk_widget_show (button23n);
  gtk_fixed_put (GTK_FIXED (fixed11), button23n, 448, 184);
  gtk_widget_set_size_request (button23n, 68, 29);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button23n), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox18), label50, FALSE, FALSE, 0);

  button24n = gtk_button_new ();
  gtk_widget_show (button24n);
  gtk_fixed_put (GTK_FIXED (fixed11), button24n, 464, 256);
  gtk_widget_set_size_request (button24n, 68, 29);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button24n), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("quitter"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox19), label51, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview2n, "row_activated",
                    G_CALLBACK (on_treeview2n_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button10n, "clicked",
                    G_CALLBACK (on_button10n_clicked),
                    NULL);
  g_signal_connect ((gpointer) button23n, "clicked",
                    G_CALLBACK (on_button23n_clicked),
                    NULL);
  g_signal_connect ((gpointer) button24n, "clicked",
                    G_CALLBACK (on_button24n_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (GestionEvent, GestionEvent, "GestionEvent");
  GLADE_HOOKUP_OBJECT (GestionEvent, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (GestionEvent, scrolledwindow2n, "scrolledwindow2n");
  GLADE_HOOKUP_OBJECT (GestionEvent, treeview2n, "treeview2n");
  GLADE_HOOKUP_OBJECT (GestionEvent, button10n, "button10n");
  GLADE_HOOKUP_OBJECT (GestionEvent, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (GestionEvent, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (GestionEvent, image9, "image9");
  GLADE_HOOKUP_OBJECT (GestionEvent, label1, "label1");
  GLADE_HOOKUP_OBJECT (GestionEvent, button23n, "button23n");
  GLADE_HOOKUP_OBJECT (GestionEvent, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (GestionEvent, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (GestionEvent, image18, "image18");
  GLADE_HOOKUP_OBJECT (GestionEvent, label50, "label50");
  GLADE_HOOKUP_OBJECT (GestionEvent, button24n, "button24n");
  GLADE_HOOKUP_OBJECT (GestionEvent, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (GestionEvent, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (GestionEvent, image19, "image19");
  GLADE_HOOKUP_OBJECT (GestionEvent, label51, "label51");

  return GestionEvent;
}

GtkWidget*
create_AjouterEvent (void)
{
  GtkWidget *AjouterEvent;
  GtkWidget *fixed12;
  GtkWidget *label32n;
  GtkWidget *label36n;
  GtkWidget *label34n;
  GtkWidget *label33n;
  GtkObject *spinbutton2n_adj;
  GtkWidget *spinbutton2n;
  GtkObject *spinbutton3n_adj;
  GtkWidget *spinbutton3n;
  GtkObject *spinbutton4n_adj;
  GtkWidget *spinbutton4n;
  GtkWidget *button11n;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label8;
  GtkWidget *entry11n;
  GtkWidget *entry12n;
  GtkWidget *comboboxentry1n;
  GtkWidget *label48n;
  GtkWidget *label49n;
  GtkWidget *label50n;

  AjouterEvent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (AjouterEvent), _("AjouterEvent"));

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (AjouterEvent), fixed12);

  label32n = gtk_label_new (_("identifiant :"));
  gtk_widget_show (label32n);
  gtk_fixed_put (GTK_FIXED (fixed12), label32n, 16, 24);
  gtk_widget_set_size_request (label32n, 112, 25);

  label36n = gtk_label_new (_("frais d inscription:"));
  gtk_widget_show (label36n);
  gtk_fixed_put (GTK_FIXED (fixed12), label36n, 0, 160);
  gtk_widget_set_size_request (label36n, 152, 33);

  label34n = gtk_label_new (_("date:"));
  gtk_widget_show (label34n);
  gtk_fixed_put (GTK_FIXED (fixed12), label34n, 32, 120);
  gtk_widget_set_size_request (label34n, 81, 25);

  label33n = gtk_label_new (_("nom:"));
  gtk_widget_show (label33n);
  gtk_fixed_put (GTK_FIXED (fixed12), label33n, 32, 64);
  gtk_widget_set_size_request (label33n, 73, 17);

  spinbutton2n_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton2n = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2n_adj), 1, 0);
  gtk_widget_show (spinbutton2n);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton2n, 120, 120);
  gtk_widget_set_size_request (spinbutton2n, 60, 27);

  spinbutton3n_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton3n = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3n_adj), 1, 0);
  gtk_widget_show (spinbutton3n);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton3n, 176, 120);
  gtk_widget_set_size_request (spinbutton3n, 60, 27);

  spinbutton4n_adj = gtk_adjustment_new (2018, 2018, 2050, 1, 10, 10);
  spinbutton4n = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4n_adj), 1, 0);
  gtk_widget_show (spinbutton4n);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton4n, 232, 120);
  gtk_widget_set_size_request (spinbutton4n, 60, 27);

  button11n = gtk_button_new ();
  gtk_widget_show (button11n);
  gtk_fixed_put (GTK_FIXED (fixed12), button11n, 168, 216);
  gtk_widget_set_size_request (button11n, 152, 53);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button11n), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox10), label8, FALSE, FALSE, 0);

  entry11n = gtk_entry_new ();
  gtk_widget_show (entry11n);
  gtk_fixed_put (GTK_FIXED (fixed12), entry11n, 136, 24);
  gtk_widget_set_size_request (entry11n, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11n), 8226);

  entry12n = gtk_entry_new ();
  gtk_widget_show (entry12n);
  gtk_fixed_put (GTK_FIXED (fixed12), entry12n, 144, 72);
  gtk_widget_set_size_request (entry12n, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12n), 8226);

  comboboxentry1n = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1n);
  gtk_fixed_put (GTK_FIXED (fixed12), comboboxentry1n, 152, 160);
  gtk_widget_set_size_request (comboboxentry1n, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1n), _("50_dinars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1n), _("70_dinars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1n), _("80_ dinars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1n), _("100_dinars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1n), _("120_dinars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1n), _("150_dinars"));

  label48n = gtk_label_new ("");
  gtk_widget_show (label48n);
  gtk_fixed_put (GTK_FIXED (fixed12), label48n, 304, 32);
  gtk_widget_set_size_request (label48n, 49, 17);

  label49n = gtk_label_new ("");
  gtk_widget_show (label49n);
  gtk_fixed_put (GTK_FIXED (fixed12), label49n, 328, 80);
  gtk_widget_set_size_request (label49n, 49, 17);

  label50n = gtk_label_new ("");
  gtk_widget_show (label50n);
  gtk_fixed_put (GTK_FIXED (fixed12), label50n, 120, 288);
  gtk_widget_set_size_request (label50n, 248, 25);

  g_signal_connect ((gpointer) button11n, "clicked",
                    G_CALLBACK (on_button11n_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (AjouterEvent, AjouterEvent, "AjouterEvent");
  GLADE_HOOKUP_OBJECT (AjouterEvent, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (AjouterEvent, label32n, "label32n");
  GLADE_HOOKUP_OBJECT (AjouterEvent, label36n, "label36n");
  GLADE_HOOKUP_OBJECT (AjouterEvent, label34n, "label34n");
  GLADE_HOOKUP_OBJECT (AjouterEvent, label33n, "label33n");
  GLADE_HOOKUP_OBJECT (AjouterEvent, spinbutton2n, "spinbutton2n");
  GLADE_HOOKUP_OBJECT (AjouterEvent, spinbutton3n, "spinbutton3n");
  GLADE_HOOKUP_OBJECT (AjouterEvent, spinbutton4n, "spinbutton4n");
  GLADE_HOOKUP_OBJECT (AjouterEvent, button11n, "button11n");
  GLADE_HOOKUP_OBJECT (AjouterEvent, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (AjouterEvent, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (AjouterEvent, image10, "image10");
  GLADE_HOOKUP_OBJECT (AjouterEvent, label8, "label8");
  GLADE_HOOKUP_OBJECT (AjouterEvent, entry11n, "entry11n");
  GLADE_HOOKUP_OBJECT (AjouterEvent, entry12n, "entry12n");
  GLADE_HOOKUP_OBJECT (AjouterEvent, comboboxentry1n, "comboboxentry1n");
  GLADE_HOOKUP_OBJECT (AjouterEvent, label48n, "label48n");
  GLADE_HOOKUP_OBJECT (AjouterEvent, label49n, "label49n");
  GLADE_HOOKUP_OBJECT (AjouterEvent, label50n, "label50n");

  return AjouterEvent;
}

GtkWidget*
create_ModifEvent (void)
{
  GtkWidget *ModifEvent;
  GtkWidget *fixed13;
  GtkWidget *label37n;
  GtkWidget *label38n;
  GtkWidget *label39n;
  GtkWidget *label40;
  GtkWidget *entry13n;
  GtkWidget *entry14n;
  GtkObject *spinbutton5n_adj;
  GtkWidget *spinbutton5n;
  GtkObject *spinbutton6n_adj;
  GtkWidget *spinbutton6n;
  GtkObject *spinbutton7n_adj;
  GtkWidget *spinbutton7n;
  GtkWidget *button15n;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label13;
  GtkWidget *button14n;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label12;
  GtkWidget *comboboxentry2n;

  ModifEvent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ModifEvent), _("ModifEvent"));

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (ModifEvent), fixed13);

  label37n = gtk_label_new (_("identifiant:"));
  gtk_widget_show (label37n);
  gtk_fixed_put (GTK_FIXED (fixed13), label37n, 64, 40);
  gtk_widget_set_size_request (label37n, 136, 48);

  label38n = gtk_label_new (_("nom:"));
  gtk_widget_show (label38n);
  gtk_fixed_put (GTK_FIXED (fixed13), label38n, 96, 104);
  gtk_widget_set_size_request (label38n, 80, 41);

  label39n = gtk_label_new (_("date:"));
  gtk_widget_show (label39n);
  gtk_fixed_put (GTK_FIXED (fixed13), label39n, 96, 176);
  gtk_widget_set_size_request (label39n, 80, 33);

  label40 = gtk_label_new (_("frais d inscription:"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed13), label40, 56, 232);
  gtk_widget_set_size_request (label40, 168, 49);

  entry13n = gtk_entry_new ();
  gtk_widget_show (entry13n);
  gtk_fixed_put (GTK_FIXED (fixed13), entry13n, 200, 48);
  gtk_widget_set_size_request (entry13n, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13n), 8226);

  entry14n = gtk_entry_new ();
  gtk_widget_show (entry14n);
  gtk_fixed_put (GTK_FIXED (fixed13), entry14n, 208, 112);
  gtk_widget_set_size_request (entry14n, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14n), 8226);

  spinbutton5n_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton5n = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5n_adj), 1, 0);
  gtk_widget_show (spinbutton5n);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton5n, 192, 176);
  gtk_widget_set_size_request (spinbutton5n, 60, 27);

  spinbutton6n_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton6n = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6n_adj), 1, 0);
  gtk_widget_show (spinbutton6n);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton6n, 248, 176);
  gtk_widget_set_size_request (spinbutton6n, 60, 27);

  spinbutton7n_adj = gtk_adjustment_new (2018, 2018, 2050, 1, 10, 10);
  spinbutton7n = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7n_adj), 1, 0);
  gtk_widget_show (spinbutton7n);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton7n, 304, 176);
  gtk_widget_set_size_request (spinbutton7n, 60, 27);

  button15n = gtk_button_new ();
  gtk_widget_show (button15n);
  gtk_fixed_put (GTK_FIXED (fixed13), button15n, 280, 312);
  gtk_widget_set_size_request (button15n, 152, 53);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button15n), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox12), label13, FALSE, FALSE, 0);

  button14n = gtk_button_new ();
  gtk_widget_show (button14n);
  gtk_fixed_put (GTK_FIXED (fixed13), button14n, 32, 312);
  gtk_widget_set_size_request (button14n, 152, 56);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button14n), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox11), label12, FALSE, FALSE, 0);

  comboboxentry2n = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry2n);
  gtk_fixed_put (GTK_FIXED (fixed13), comboboxentry2n, 224, 240);
  gtk_widget_set_size_request (comboboxentry2n, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2n), _("50_dinars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2n), _("70_dinars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2n), _("80_dinars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2n), _("100_dinars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2n), _("120_dinars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2n), _("150_dinars"));

  g_signal_connect ((gpointer) button15n, "clicked",
                    G_CALLBACK (on_button15n_clicked),
                    NULL);
  g_signal_connect ((gpointer) button14n, "clicked",
                    G_CALLBACK (on_button14n_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ModifEvent, ModifEvent, "ModifEvent");
  GLADE_HOOKUP_OBJECT (ModifEvent, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (ModifEvent, label37n, "label37n");
  GLADE_HOOKUP_OBJECT (ModifEvent, label38n, "label38n");
  GLADE_HOOKUP_OBJECT (ModifEvent, label39n, "label39n");
  GLADE_HOOKUP_OBJECT (ModifEvent, label40, "label40");
  GLADE_HOOKUP_OBJECT (ModifEvent, entry13n, "entry13n");
  GLADE_HOOKUP_OBJECT (ModifEvent, entry14n, "entry14n");
  GLADE_HOOKUP_OBJECT (ModifEvent, spinbutton5n, "spinbutton5n");
  GLADE_HOOKUP_OBJECT (ModifEvent, spinbutton6n, "spinbutton6n");
  GLADE_HOOKUP_OBJECT (ModifEvent, spinbutton7n, "spinbutton7n");
  GLADE_HOOKUP_OBJECT (ModifEvent, button15n, "button15n");
  GLADE_HOOKUP_OBJECT (ModifEvent, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (ModifEvent, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (ModifEvent, image12, "image12");
  GLADE_HOOKUP_OBJECT (ModifEvent, label13, "label13");
  GLADE_HOOKUP_OBJECT (ModifEvent, button14n, "button14n");
  GLADE_HOOKUP_OBJECT (ModifEvent, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (ModifEvent, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (ModifEvent, image11, "image11");
  GLADE_HOOKUP_OBJECT (ModifEvent, label12, "label12");
  GLADE_HOOKUP_OBJECT (ModifEvent, comboboxentry2n, "comboboxentry2n");

  return ModifEvent;
}

GtkWidget*
create_Profils (void)
{
  GtkWidget *Profils;
  GtkWidget *fixed14;
  GtkWidget *button17n;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label41;
  GtkWidget *scrolledwindow3n;
  GtkWidget *treeview3n;
  GtkWidget *combobox4n;

  Profils = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Profils), _("Profils"));

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (Profils), fixed14);

  button17n = gtk_button_new ();
  gtk_widget_show (button17n);
  gtk_fixed_put (GTK_FIXED (fixed14), button17n, 280, 368);
  gtk_widget_set_size_request (button17n, 144, 37);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button17n), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox13), label41, FALSE, FALSE, 0);

  scrolledwindow3n = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3n);
  gtk_fixed_put (GTK_FIXED (fixed14), scrolledwindow3n, 63, 90);
  gtk_widget_set_size_request (scrolledwindow3n, 650, 252);

  treeview3n = gtk_tree_view_new ();
  gtk_widget_show (treeview3n);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3n), treeview3n);

  combobox4n = gtk_combo_box_new_text ();
  gtk_widget_show (combobox4n);
  gtk_fixed_put (GTK_FIXED (fixed14), combobox4n, 202, 16);
  gtk_widget_set_size_request (combobox4n, 250, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4n), _("medecin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4n), _("coach"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4n), _("adherent"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4n), _("kinesi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4n), _("dieteticien"));

  g_signal_connect ((gpointer) button17n, "clicked",
                    G_CALLBACK (on_button17n_clicked),
                    NULL);
  g_signal_connect ((gpointer) combobox4n, "changed",
                    G_CALLBACK (on_combobox4n_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Profils, Profils, "Profils");
  GLADE_HOOKUP_OBJECT (Profils, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (Profils, button17n, "button17n");
  GLADE_HOOKUP_OBJECT (Profils, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Profils, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Profils, image13, "image13");
  GLADE_HOOKUP_OBJECT (Profils, label41, "label41");
  GLADE_HOOKUP_OBJECT (Profils, scrolledwindow3n, "scrolledwindow3n");
  GLADE_HOOKUP_OBJECT (Profils, treeview3n, "treeview3n");
  GLADE_HOOKUP_OBJECT (Profils, combobox4n, "combobox4n");

  return Profils;
}

GtkWidget*
create_ModifCompte (void)
{
  GtkWidget *ModifCompte;
  GtkWidget *fixed15;
  GtkWidget *label45n;
  GtkWidget *label44n;
  GtkWidget *label43n;
  GtkWidget *label42n;
  GtkWidget *entry15n;
  GtkWidget *entry16n;
  GtkWidget *entry17n;
  GtkWidget *entry18n;
  GtkWidget *button18n;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label46;
  GtkWidget *button20n;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label47;

  ModifCompte = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ModifCompte), _("ModifCompte"));

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (ModifCompte), fixed15);

  label45n = gtk_label_new (_("identifiant:"));
  gtk_widget_show (label45n);
  gtk_fixed_put (GTK_FIXED (fixed15), label45n, 32, 184);
  gtk_widget_set_size_request (label45n, 97, 17);

  label44n = gtk_label_new (_("role:"));
  gtk_widget_show (label44n);
  gtk_fixed_put (GTK_FIXED (fixed15), label44n, 40, 144);
  gtk_widget_set_size_request (label44n, 89, 17);

  label43n = gtk_label_new (_("password:"));
  gtk_widget_show (label43n);
  gtk_fixed_put (GTK_FIXED (fixed15), label43n, 32, 96);
  gtk_widget_set_size_request (label43n, 81, 17);

  label42n = gtk_label_new (_("login:"));
  gtk_widget_show (label42n);
  gtk_fixed_put (GTK_FIXED (fixed15), label42n, 40, 48);
  gtk_widget_set_size_request (label42n, 73, 17);

  entry15n = gtk_entry_new ();
  gtk_widget_show (entry15n);
  gtk_fixed_put (GTK_FIXED (fixed15), entry15n, 144, 48);
  gtk_widget_set_size_request (entry15n, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15n), 8226);

  entry16n = gtk_entry_new ();
  gtk_widget_show (entry16n);
  gtk_fixed_put (GTK_FIXED (fixed15), entry16n, 152, 96);
  gtk_widget_set_size_request (entry16n, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry16n), 8226);

  entry17n = gtk_entry_new ();
  gtk_widget_show (entry17n);
  gtk_fixed_put (GTK_FIXED (fixed15), entry17n, 152, 136);
  gtk_widget_set_size_request (entry17n, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry17n), 8226);

  entry18n = gtk_entry_new ();
  gtk_widget_show (entry18n);
  gtk_fixed_put (GTK_FIXED (fixed15), entry18n, 168, 184);
  gtk_widget_set_size_request (entry18n, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry18n), 8226);

  button18n = gtk_button_new ();
  gtk_widget_show (button18n);
  gtk_fixed_put (GTK_FIXED (fixed15), button18n, 64, 240);
  gtk_widget_set_size_request (button18n, 136, 37);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button18n), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox14), label46, FALSE, FALSE, 0);

  button20n = gtk_button_new ();
  gtk_widget_show (button20n);
  gtk_fixed_put (GTK_FIXED (fixed15), button20n, 264, 240);
  gtk_widget_set_size_request (button20n, 120, 37);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button20n), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox15), label47, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button18n, "clicked",
                    G_CALLBACK (on_button18n_clicked),
                    NULL);
  g_signal_connect ((gpointer) button20n, "clicked",
                    G_CALLBACK (on_button20n_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ModifCompte, ModifCompte, "ModifCompte");
  GLADE_HOOKUP_OBJECT (ModifCompte, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (ModifCompte, label45n, "label45n");
  GLADE_HOOKUP_OBJECT (ModifCompte, label44n, "label44n");
  GLADE_HOOKUP_OBJECT (ModifCompte, label43n, "label43n");
  GLADE_HOOKUP_OBJECT (ModifCompte, label42n, "label42n");
  GLADE_HOOKUP_OBJECT (ModifCompte, entry15n, "entry15n");
  GLADE_HOOKUP_OBJECT (ModifCompte, entry16n, "entry16n");
  GLADE_HOOKUP_OBJECT (ModifCompte, entry17n, "entry17n");
  GLADE_HOOKUP_OBJECT (ModifCompte, entry18n, "entry18n");
  GLADE_HOOKUP_OBJECT (ModifCompte, button18n, "button18n");
  GLADE_HOOKUP_OBJECT (ModifCompte, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (ModifCompte, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (ModifCompte, image14, "image14");
  GLADE_HOOKUP_OBJECT (ModifCompte, label46, "label46");
  GLADE_HOOKUP_OBJECT (ModifCompte, button20n, "button20n");
  GLADE_HOOKUP_OBJECT (ModifCompte, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (ModifCompte, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (ModifCompte, image15, "image15");
  GLADE_HOOKUP_OBJECT (ModifCompte, label47, "label47");

  return ModifCompte;
}

