/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_login (void);
GtkWidget* create_Admin (void);
GtkWidget* create_coach (void);
GtkWidget* create_adherent (void);
GtkWidget* create_medecin (void);
GtkWidget* create_kinesitherapeute (void);
GtkWidget* create_dieteticien (void);
GtkWidget* create_ProfilAdmin (void);
GtkWidget* create_GestionCompte (void);
GtkWidget* create_AjouterCompte (void);
GtkWidget* create_GestionEvent (void);
GtkWidget* create_AjouterEvent (void);
GtkWidget* create_ModifEvent (void);
GtkWidget* create_Profils (void);
GtkWidget* create_ModifCompte (void);
