/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1y (void)
{
  GtkWidget *window1y;
  GtkWidget *fixed1;
  GtkWidget *entry1y;
  GtkWidget *entry2y;
  GtkWidget *label5y;
  GtkWidget *checkbutton1y;
  GtkWidget *label6y;
  GtkWidget *label1y;
  GtkWidget *label2y;
  GtkWidget *button1y;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label3;
  GtkWidget *button2y;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label4;

  window1y = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1y), _("window1y"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1y), fixed1);

  entry1y = gtk_entry_new ();
  gtk_widget_show (entry1y);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1y, 144, 72);
  gtk_widget_set_size_request (entry1y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1y), 8226);

  entry2y = gtk_entry_new ();
  gtk_widget_show (entry2y);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2y, 144, 120);
  gtk_widget_set_size_request (entry2y, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entry2y), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2y), 8226);

  label5y = gtk_label_new ("");
  gtk_widget_show (label5y);
  gtk_fixed_put (GTK_FIXED (fixed1), label5y, 88, 216);
  gtk_widget_set_size_request (label5y, 280, 48);

  checkbutton1y = gtk_check_button_new_with_mnemonic (_("visibilit\303\251"));
  gtk_widget_show (checkbutton1y);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton1y, 160, 152);
  gtk_widget_set_size_request (checkbutton1y, 121, 24);

  label6y = gtk_label_new (_("Authentification"));
  gtk_widget_show (label6y);
  gtk_fixed_put (GTK_FIXED (fixed1), label6y, 136, 0);
  gtk_widget_set_size_request (label6y, 184, 40);

  label1y = gtk_label_new (_("Identifiant:"));
  gtk_widget_show (label1y);
  gtk_fixed_put (GTK_FIXED (fixed1), label1y, 24, 72);
  gtk_widget_set_size_request (label1y, 112, 24);

  label2y = gtk_label_new (_("Mot de passe:"));
  gtk_widget_show (label2y);
  gtk_fixed_put (GTK_FIXED (fixed1), label2y, 16, 120);
  gtk_widget_set_size_request (label2y, 120, 24);

  button1y = gtk_button_new ();
  gtk_widget_show (button1y);
  gtk_fixed_put (GTK_FIXED (fixed1), button1y, 152, 176);
  gtk_widget_set_size_request (button1y, 120, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1y), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-connect", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Connexion"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox1), label3, FALSE, FALSE, 0);

  button2y = gtk_button_new ();
  gtk_widget_show (button2y);
  gtk_fixed_put (GTK_FIXED (fixed1), button2y, 352, 304);
  gtk_widget_set_size_request (button2y, 84, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2y), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox2), label4, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) checkbutton1y, "toggled",
                    G_CALLBACK (on_checkbutton1y_toggled),
                    NULL);
  g_signal_connect ((gpointer) button1y, "clicked",
                    G_CALLBACK (on_button1y_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2y, "clicked",
                    G_CALLBACK (on_button2y_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1y, window1y, "window1y");
  GLADE_HOOKUP_OBJECT (window1y, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1y, entry1y, "entry1y");
  GLADE_HOOKUP_OBJECT (window1y, entry2y, "entry2y");
  GLADE_HOOKUP_OBJECT (window1y, label5y, "label5y");
  GLADE_HOOKUP_OBJECT (window1y, checkbutton1y, "checkbutton1y");
  GLADE_HOOKUP_OBJECT (window1y, label6y, "label6y");
  GLADE_HOOKUP_OBJECT (window1y, label1y, "label1y");
  GLADE_HOOKUP_OBJECT (window1y, label2y, "label2y");
  GLADE_HOOKUP_OBJECT (window1y, button1y, "button1y");
  GLADE_HOOKUP_OBJECT (window1y, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1y, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1y, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1y, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1y, button2y, "button2y");
  GLADE_HOOKUP_OBJECT (window1y, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window1y, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window1y, image2, "image2");
  GLADE_HOOKUP_OBJECT (window1y, label4, "label4");

  return window1y;
}

GtkWidget*
create_window2y (void)
{
  GtkWidget *window2y;
  GtkWidget *fixed2;
  GtkWidget *label7y;
  GtkWidget *button3y;
  GtkWidget *button5y;
  GtkWidget *button6y;
  GtkWidget *button7y;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label8;
  GtkWidget *button4y;

  window2y = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2y), _("window2y"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window2y), fixed2);

  label7y = gtk_label_new (_("Espace di\303\251t\303\251tique"));
  gtk_widget_show (label7y);
  gtk_fixed_put (GTK_FIXED (fixed2), label7y, 96, 0);
  gtk_widget_set_size_request (label7y, 200, 48);

  button3y = gtk_button_new_with_mnemonic (_("Fiches"));
  gtk_widget_show (button3y);
  gtk_fixed_put (GTK_FIXED (fixed2), button3y, 120, 48);
  gtk_widget_set_size_request (button3y, 152, 48);

  button5y = gtk_button_new_with_mnemonic (_("Journal"));
  gtk_widget_show (button5y);
  gtk_fixed_put (GTK_FIXED (fixed2), button5y, 120, 144);
  gtk_widget_set_size_request (button5y, 152, 48);

  button6y = gtk_button_new_with_mnemonic (_("Disponibilit\303\251"));
  gtk_widget_show (button6y);
  gtk_fixed_put (GTK_FIXED (fixed2), button6y, 120, 192);
  gtk_widget_set_size_request (button6y, 152, 48);

  button7y = gtk_button_new ();
  gtk_widget_show (button7y);
  gtk_fixed_put (GTK_FIXED (fixed2), button7y, 296, 256);
  gtk_widget_set_size_request (button7y, 88, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button7y), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox3), label8, FALSE, FALSE, 0);

  button4y = gtk_button_new_with_mnemonic (_("Profil"));
  gtk_widget_show (button4y);
  gtk_fixed_put (GTK_FIXED (fixed2), button4y, 120, 96);
  gtk_widget_set_size_request (button4y, 152, 48);

  g_signal_connect ((gpointer) button3y, "clicked",
                    G_CALLBACK (on_button3y_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5y, "clicked",
                    G_CALLBACK (on_button5y_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6y, "clicked",
                    G_CALLBACK (on_button6y_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7y, "clicked",
                    G_CALLBACK (on_button7y_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4y, "clicked",
                    G_CALLBACK (on_button4y_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2y, window2y, "window2y");
  GLADE_HOOKUP_OBJECT (window2y, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2y, label7y, "label7y");
  GLADE_HOOKUP_OBJECT (window2y, button3y, "button3y");
  GLADE_HOOKUP_OBJECT (window2y, button5y, "button5y");
  GLADE_HOOKUP_OBJECT (window2y, button6y, "button6y");
  GLADE_HOOKUP_OBJECT (window2y, button7y, "button7y");
  GLADE_HOOKUP_OBJECT (window2y, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window2y, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window2y, image3, "image3");
  GLADE_HOOKUP_OBJECT (window2y, label8, "label8");
  GLADE_HOOKUP_OBJECT (window2y, button4y, "button4y");

  return window2y;
}

GtkWidget*
create_window3y (void)
{
  GtkWidget *window3y;
  GtkWidget *fixed3;
  GtkWidget *label9y;
  GtkWidget *button10y;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label10;
  GtkWidget *button8y;
  GtkWidget *button9y;

  window3y = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3y), _("window3y"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window3y), fixed3);

  label9y = gtk_label_new (_("Gestions fiches"));
  gtk_widget_show (label9y);
  gtk_fixed_put (GTK_FIXED (fixed3), label9y, 112, 0);
  gtk_widget_set_size_request (label9y, 152, 40);

  button10y = gtk_button_new ();
  gtk_widget_show (button10y);
  gtk_fixed_put (GTK_FIXED (fixed3), button10y, 280, 256);
  gtk_widget_set_size_request (button10y, 108, 37);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button10y), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox4), label10, FALSE, FALSE, 0);

  button8y = gtk_button_new_with_mnemonic (_("Fiches di\303\251t\303\251tiques"));
  gtk_widget_show (button8y);
  gtk_fixed_put (GTK_FIXED (fixed3), button8y, 88, 72);
  gtk_widget_set_size_request (button8y, 208, 48);

  button9y = gtk_button_new_with_mnemonic (_("Fiches m\303\251dicales"));
  gtk_widget_show (button9y);
  gtk_fixed_put (GTK_FIXED (fixed3), button9y, 88, 128);
  gtk_widget_set_size_request (button9y, 208, 48);

  g_signal_connect ((gpointer) button10y, "clicked",
                    G_CALLBACK (on_button10y_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8y, "clicked",
                    G_CALLBACK (on_button8y_clicked),
                    NULL);
  g_signal_connect ((gpointer) button9y, "clicked",
                    G_CALLBACK (on_button9y_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3y, window3y, "window3y");
  GLADE_HOOKUP_OBJECT (window3y, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window3y, label9y, "label9y");
  GLADE_HOOKUP_OBJECT (window3y, button10y, "button10y");
  GLADE_HOOKUP_OBJECT (window3y, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window3y, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window3y, image4, "image4");
  GLADE_HOOKUP_OBJECT (window3y, label10, "label10");
  GLADE_HOOKUP_OBJECT (window3y, button8y, "button8y");
  GLADE_HOOKUP_OBJECT (window3y, button9y, "button9y");

  return window3y;
}

GtkWidget*
create_window4y (void)
{
  GtkWidget *window4y;
  GtkWidget *fixed4;
  GtkWidget *label11y;
  GtkWidget *button11y;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label12;
  GtkWidget *button12y;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label13;
  GtkWidget *button13y;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label14;
  GtkWidget *button14y;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label15;
  GtkWidget *button15y;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label16;

  window4y = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window4y), _("window4y"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (window4y), fixed4);

  label11y = gtk_label_new (_("Fiches di\303\251t\303\251tiques"));
  gtk_widget_show (label11y);
  gtk_fixed_put (GTK_FIXED (fixed4), label11y, 120, 0);
  gtk_widget_set_size_request (label11y, 152, 40);

  button11y = gtk_button_new ();
  gtk_widget_show (button11y);
  gtk_fixed_put (GTK_FIXED (fixed4), button11y, 128, 64);
  gtk_widget_set_size_request (button11y, 128, 48);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button11y), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox5), label12, FALSE, FALSE, 0);

  button12y = gtk_button_new ();
  gtk_widget_show (button12y);
  gtk_fixed_put (GTK_FIXED (fixed4), button12y, 128, 112);
  gtk_widget_set_size_request (button12y, 128, 48);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button12y), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-select-all", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox6), label13, FALSE, FALSE, 0);

  button13y = gtk_button_new ();
  gtk_widget_show (button13y);
  gtk_fixed_put (GTK_FIXED (fixed4), button13y, 128, 160);
  gtk_widget_set_size_request (button13y, 128, 48);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button13y), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-revert-to-saved", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox7), label14, FALSE, FALSE, 0);

  button14y = gtk_button_new ();
  gtk_widget_show (button14y);
  gtk_fixed_put (GTK_FIXED (fixed4), button14y, 128, 208);
  gtk_widget_set_size_request (button14y, 128, 48);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button14y), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox8), label15, FALSE, FALSE, 0);

  button15y = gtk_button_new ();
  gtk_widget_show (button15y);
  gtk_fixed_put (GTK_FIXED (fixed4), button15y, 296, 256);
  gtk_widget_set_size_request (button15y, 96, 37);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button15y), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox9), label16, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button11y, "clicked",
                    G_CALLBACK (on_button11y_clicked),
                    NULL);
  g_signal_connect ((gpointer) button12y, "clicked",
                    G_CALLBACK (on_button12y_clicked),
                    NULL);
  g_signal_connect ((gpointer) button13y, "clicked",
                    G_CALLBACK (on_button13y_clicked),
                    NULL);
  g_signal_connect ((gpointer) button14y, "clicked",
                    G_CALLBACK (on_button14y_clicked),
                    NULL);
  g_signal_connect ((gpointer) button15y, "clicked",
                    G_CALLBACK (on_button15y_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4y, window4y, "window4y");
  GLADE_HOOKUP_OBJECT (window4y, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window4y, label11y, "label11y");
  GLADE_HOOKUP_OBJECT (window4y, button11y, "button11y");
  GLADE_HOOKUP_OBJECT (window4y, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window4y, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window4y, image5, "image5");
  GLADE_HOOKUP_OBJECT (window4y, label12, "label12");
  GLADE_HOOKUP_OBJECT (window4y, button12y, "button12y");
  GLADE_HOOKUP_OBJECT (window4y, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window4y, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window4y, image6, "image6");
  GLADE_HOOKUP_OBJECT (window4y, label13, "label13");
  GLADE_HOOKUP_OBJECT (window4y, button13y, "button13y");
  GLADE_HOOKUP_OBJECT (window4y, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window4y, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window4y, image7, "image7");
  GLADE_HOOKUP_OBJECT (window4y, label14, "label14");
  GLADE_HOOKUP_OBJECT (window4y, button14y, "button14y");
  GLADE_HOOKUP_OBJECT (window4y, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window4y, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window4y, image8, "image8");
  GLADE_HOOKUP_OBJECT (window4y, label15, "label15");
  GLADE_HOOKUP_OBJECT (window4y, button15y, "button15y");
  GLADE_HOOKUP_OBJECT (window4y, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window4y, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window4y, image9, "image9");
  GLADE_HOOKUP_OBJECT (window4y, label16, "label16");

  return window4y;
}

GtkWidget*
create_window5y (void)
{
  GtkWidget *window5y;
  GtkWidget *fixed5;
  GtkWidget *entry3y;
  GtkWidget *entry4y;
  GtkWidget *entry5y;
  GtkWidget *entry9y;
  GtkWidget *entry6y;
  GtkWidget *entry7y;
  GtkWidget *entry8y;
  GtkWidget *label17y;
  GtkWidget *label18y;
  GtkWidget *label19y;
  GtkWidget *label20y;
  GtkWidget *label21y;
  GtkWidget *label22y;
  GtkWidget *label23y;
  GtkWidget *label24y;
  GtkWidget *combobox1y;
  GtkWidget *combobox2y;
  GtkWidget *combobox3y;
  GtkWidget *label25y;
  GtkWidget *combobox4y;
  GtkWidget *label26y;
  GtkWidget *label27y;
  GtkWidget *label28y;
  GtkWidget *label29y;
  GtkWidget *label30y;
  GtkWidget *combobox5y;
  GtkWidget *button16y;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label32;
  GtkWidget *button17y;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label33;

  window5y = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window5y), _("window5y"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window5y), fixed5);

  entry3y = gtk_entry_new ();
  gtk_widget_show (entry3y);
  gtk_fixed_put (GTK_FIXED (fixed5), entry3y, 80, 56);
  gtk_widget_set_size_request (entry3y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3y), 8226);

  entry4y = gtk_entry_new ();
  gtk_widget_show (entry4y);
  gtk_fixed_put (GTK_FIXED (fixed5), entry4y, 80, 88);
  gtk_widget_set_size_request (entry4y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4y), 8226);

  entry5y = gtk_entry_new ();
  gtk_widget_show (entry5y);
  gtk_fixed_put (GTK_FIXED (fixed5), entry5y, 80, 120);
  gtk_widget_set_size_request (entry5y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5y), 8226);

  entry9y = gtk_entry_new ();
  gtk_widget_show (entry9y);
  gtk_fixed_put (GTK_FIXED (fixed5), entry9y, 152, 416);
  gtk_widget_set_size_request (entry9y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9y), 8226);

  entry6y = gtk_entry_new ();
  gtk_widget_show (entry6y);
  gtk_fixed_put (GTK_FIXED (fixed5), entry6y, 64, 264);
  gtk_widget_set_size_request (entry6y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6y), 8226);

  entry7y = gtk_entry_new ();
  gtk_widget_show (entry7y);
  gtk_fixed_put (GTK_FIXED (fixed5), entry7y, 72, 296);
  gtk_widget_set_size_request (entry7y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7y), 8226);

  entry8y = gtk_entry_new ();
  gtk_widget_show (entry8y);
  gtk_fixed_put (GTK_FIXED (fixed5), entry8y, 64, 336);
  gtk_widget_set_size_request (entry8y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8y), 106);

  label17y = gtk_label_new (_("Ajouter patient"));
  gtk_widget_show (label17y);
  gtk_fixed_put (GTK_FIXED (fixed5), label17y, 184, 0);
  gtk_widget_set_size_request (label17y, 160, 40);

  label18y = gtk_label_new (_("Nom:"));
  gtk_widget_show (label18y);
  gtk_fixed_put (GTK_FIXED (fixed5), label18y, 0, 56);
  gtk_widget_set_size_request (label18y, 72, 24);

  label19y = gtk_label_new (_("Prenom:"));
  gtk_widget_show (label19y);
  gtk_fixed_put (GTK_FIXED (fixed5), label19y, 0, 88);
  gtk_widget_set_size_request (label19y, 72, 24);

  label20y = gtk_label_new (_("CIN:"));
  gtk_widget_show (label20y);
  gtk_fixed_put (GTK_FIXED (fixed5), label20y, 8, 120);
  gtk_widget_set_size_request (label20y, 56, 24);

  label21y = gtk_label_new (_("Date de naissance:"));
  gtk_widget_show (label21y);
  gtk_fixed_put (GTK_FIXED (fixed5), label21y, 0, 168);
  gtk_widget_set_size_request (label21y, 144, 32);

  label22y = gtk_label_new (_("Jour"));
  gtk_widget_show (label22y);
  gtk_fixed_put (GTK_FIXED (fixed5), label22y, 168, 152);
  gtk_widget_set_size_request (label22y, 49, 17);

  label23y = gtk_label_new (_("Mois"));
  gtk_widget_show (label23y);
  gtk_fixed_put (GTK_FIXED (fixed5), label23y, 256, 152);
  gtk_widget_set_size_request (label23y, 49, 17);

  label24y = gtk_label_new (_("Annee"));
  gtk_widget_show (label24y);
  gtk_fixed_put (GTK_FIXED (fixed5), label24y, 344, 152);
  gtk_widget_set_size_request (label24y, 49, 17);

  combobox1y = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1y);
  gtk_fixed_put (GTK_FIXED (fixed5), combobox1y, 160, 168);
  gtk_widget_set_size_request (combobox1y, 72, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("01"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("02"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("03"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("04"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("05"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("06"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("07"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("08"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("09"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("20"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("21"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("23"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("24"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("25"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("26"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("27"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("28"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("29"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1y), _("31"));

  combobox2y = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2y);
  gtk_fixed_put (GTK_FIXED (fixed5), combobox2y, 248, 168);
  gtk_widget_set_size_request (combobox2y, 72, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2y), _("01"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2y), _("02"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2y), _("03"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2y), _("04"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2y), _("05"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2y), _("06"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2y), _("07"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2y), _("08"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2y), _("09"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2y), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2y), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2y), _("12"));

  combobox3y = gtk_combo_box_new_text ();
  gtk_widget_show (combobox3y);
  gtk_fixed_put (GTK_FIXED (fixed5), combobox3y, 336, 168);
  gtk_widget_set_size_request (combobox3y, 72, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3y), _("2018"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3y), _("2019"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3y), _("2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3y), _("2021"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3y), _("2022"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3y), _("2023"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3y), _("2024"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3y), _("2025"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3y), _("2026"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3y), _("2027"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3y), _("2028"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3y), _("2029"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3y), _("2030"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3y), _("2031"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3y), _("2032"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3y), _("2033"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3y), _("2034"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3y), _("2035"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3y), _("2036"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3y), _("2037"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3y), _("2038"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3y), _("2039"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3y), _("2040"));

  label25y = gtk_label_new (_("Sexe:"));
  gtk_widget_show (label25y);
  gtk_fixed_put (GTK_FIXED (fixed5), label25y, 8, 224);
  gtk_widget_set_size_request (label25y, 56, 24);

  combobox4y = gtk_combo_box_new_text ();
  gtk_widget_show (combobox4y);
  gtk_fixed_put (GTK_FIXED (fixed5), combobox4y, 56, 216);
  gtk_widget_set_size_request (combobox4y, 136, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4y), _("femme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox4y), _("homme"));

  label26y = gtk_label_new (_("Taille:"));
  gtk_widget_show (label26y);
  gtk_fixed_put (GTK_FIXED (fixed5), label26y, 0, 264);
  gtk_widget_set_size_request (label26y, 72, 24);

  label27y = gtk_label_new (_("Poids:"));
  gtk_widget_show (label27y);
  gtk_fixed_put (GTK_FIXED (fixed5), label27y, 16, 304);
  gtk_widget_set_size_request (label27y, 49, 17);

  label28y = gtk_label_new (_("IMC:"));
  gtk_widget_show (label28y);
  gtk_fixed_put (GTK_FIXED (fixed5), label28y, 16, 344);
  gtk_widget_set_size_request (label28y, 49, 17);

  label29y = gtk_label_new (_("Classification:"));
  gtk_widget_show (label29y);
  gtk_fixed_put (GTK_FIXED (fixed5), label29y, 0, 376);
  gtk_widget_set_size_request (label29y, 112, 24);

  label30y = gtk_label_new (_("Regime alimentaire:"));
  gtk_widget_show (label30y);
  gtk_fixed_put (GTK_FIXED (fixed5), label30y, 0, 416);
  gtk_widget_set_size_request (label30y, 152, 24);

  combobox5y = gtk_combo_box_new_text ();
  gtk_widget_show (combobox5y);
  gtk_fixed_put (GTK_FIXED (fixed5), combobox5y, 112, 376);
  gtk_widget_set_size_request (combobox5y, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5y), _("ob\303\251sit\303\251 mod\303\251r\303\251"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5y), _("ob\303\251sit\303\251 s\303\251v\303\251re"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5y), _("ob\303\251sit\303\251 morbide"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5y), _("surpoids"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5y), _("poids id\303\251als"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox5y), _("poids insuffisant"));

  button16y = gtk_button_new ();
  gtk_widget_show (button16y);
  gtk_fixed_put (GTK_FIXED (fixed5), button16y, 160, 464);
  gtk_widget_set_size_request (button16y, 136, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button16y), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox10), label32, FALSE, FALSE, 0);

  button17y = gtk_button_new ();
  gtk_widget_show (button17y);
  gtk_fixed_put (GTK_FIXED (fixed5), button17y, 440, 520);
  gtk_widget_set_size_request (button17y, 96, 40);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button17y), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox11), label33, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button16y, "clicked",
                    G_CALLBACK (on_button16y_clicked),
                    NULL);
  g_signal_connect ((gpointer) button17y, "clicked",
                    G_CALLBACK (on_button17y_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window5y, window5y, "window5y");
  GLADE_HOOKUP_OBJECT (window5y, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window5y, entry3y, "entry3y");
  GLADE_HOOKUP_OBJECT (window5y, entry4y, "entry4y");
  GLADE_HOOKUP_OBJECT (window5y, entry5y, "entry5y");
  GLADE_HOOKUP_OBJECT (window5y, entry9y, "entry9y");
  GLADE_HOOKUP_OBJECT (window5y, entry6y, "entry6y");
  GLADE_HOOKUP_OBJECT (window5y, entry7y, "entry7y");
  GLADE_HOOKUP_OBJECT (window5y, entry8y, "entry8y");
  GLADE_HOOKUP_OBJECT (window5y, label17y, "label17y");
  GLADE_HOOKUP_OBJECT (window5y, label18y, "label18y");
  GLADE_HOOKUP_OBJECT (window5y, label19y, "label19y");
  GLADE_HOOKUP_OBJECT (window5y, label20y, "label20y");
  GLADE_HOOKUP_OBJECT (window5y, label21y, "label21y");
  GLADE_HOOKUP_OBJECT (window5y, label22y, "label22y");
  GLADE_HOOKUP_OBJECT (window5y, label23y, "label23y");
  GLADE_HOOKUP_OBJECT (window5y, label24y, "label24y");
  GLADE_HOOKUP_OBJECT (window5y, combobox1y, "combobox1y");
  GLADE_HOOKUP_OBJECT (window5y, combobox2y, "combobox2y");
  GLADE_HOOKUP_OBJECT (window5y, combobox3y, "combobox3y");
  GLADE_HOOKUP_OBJECT (window5y, label25y, "label25y");
  GLADE_HOOKUP_OBJECT (window5y, combobox4y, "combobox4y");
  GLADE_HOOKUP_OBJECT (window5y, label26y, "label26y");
  GLADE_HOOKUP_OBJECT (window5y, label27y, "label27y");
  GLADE_HOOKUP_OBJECT (window5y, label28y, "label28y");
  GLADE_HOOKUP_OBJECT (window5y, label29y, "label29y");
  GLADE_HOOKUP_OBJECT (window5y, label30y, "label30y");
  GLADE_HOOKUP_OBJECT (window5y, combobox5y, "combobox5y");
  GLADE_HOOKUP_OBJECT (window5y, button16y, "button16y");
  GLADE_HOOKUP_OBJECT (window5y, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window5y, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window5y, image10, "image10");
  GLADE_HOOKUP_OBJECT (window5y, label32, "label32");
  GLADE_HOOKUP_OBJECT (window5y, button17y, "button17y");
  GLADE_HOOKUP_OBJECT (window5y, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window5y, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window5y, image11, "image11");
  GLADE_HOOKUP_OBJECT (window5y, label33, "label33");

  return window5y;
}

GtkWidget*
create_window6y (void)
{
  GtkWidget *window6y;
  GtkWidget *fixed6;
  GtkWidget *entry21y;
  GtkWidget *label59y;
  GtkWidget *button18y;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label35;
  GtkWidget *button26y;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label57;
  GtkWidget *button19y;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label36;
  GtkWidget *label34y;

  window6y = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window6y), _("window6y"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (window6y), fixed6);

  entry21y = gtk_entry_new ();
  gtk_widget_show (entry21y);
  gtk_fixed_put (GTK_FIXED (fixed6), entry21y, 112, 88);
  gtk_widget_set_size_request (entry21y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry21y), 8226);

  label59y = gtk_label_new ("");
  gtk_widget_show (label59y);
  gtk_fixed_put (GTK_FIXED (fixed6), label59y, 96, 176);
  gtk_widget_set_size_request (label59y, 185, 32);

  button18y = gtk_button_new ();
  gtk_widget_show (button18y);
  gtk_fixed_put (GTK_FIXED (fixed6), button18y, 64, 136);
  gtk_widget_set_size_request (button18y, 104, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button18y), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-revert-to-saved", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox12), label35, FALSE, FALSE, 0);

  button26y = gtk_button_new ();
  gtk_widget_show (button26y);
  gtk_fixed_put (GTK_FIXED (fixed6), button26y, 192, 136);
  gtk_widget_set_size_request (button26y, 104, 32);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button26y), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label57 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox19), label57, FALSE, FALSE, 0);

  button19y = gtk_button_new ();
  gtk_widget_show (button19y);
  gtk_fixed_put (GTK_FIXED (fixed6), button19y, 280, 248);
  gtk_widget_set_size_request (button19y, 84, 32);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button19y), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox13), label36, FALSE, FALSE, 0);

  label34y = gtk_label_new (_("Entrer  CIN:"));
  gtk_widget_show (label34y);
  gtk_fixed_put (GTK_FIXED (fixed6), label34y, 112, 32);
  gtk_widget_set_size_request (label34y, 152, 32);

  g_signal_connect ((gpointer) button18y, "clicked",
                    G_CALLBACK (on_button18y_clicked),
                    NULL);
  g_signal_connect ((gpointer) button26y, "clicked",
                    G_CALLBACK (on_button26y_clicked),
                    NULL);
  g_signal_connect ((gpointer) button19y, "clicked",
                    G_CALLBACK (on_button19y_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window6y, window6y, "window6y");
  GLADE_HOOKUP_OBJECT (window6y, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window6y, entry21y, "entry21y");
  GLADE_HOOKUP_OBJECT (window6y, label59y, "label59y");
  GLADE_HOOKUP_OBJECT (window6y, button18y, "button18y");
  GLADE_HOOKUP_OBJECT (window6y, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window6y, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window6y, image12, "image12");
  GLADE_HOOKUP_OBJECT (window6y, label35, "label35");
  GLADE_HOOKUP_OBJECT (window6y, button26y, "button26y");
  GLADE_HOOKUP_OBJECT (window6y, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (window6y, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (window6y, image19, "image19");
  GLADE_HOOKUP_OBJECT (window6y, label57, "label57");
  GLADE_HOOKUP_OBJECT (window6y, button19y, "button19y");
  GLADE_HOOKUP_OBJECT (window6y, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window6y, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window6y, image13, "image13");
  GLADE_HOOKUP_OBJECT (window6y, label36, "label36");
  GLADE_HOOKUP_OBJECT (window6y, label34y, "label34y");

  return window6y;
}

GtkWidget*
create_window7y (void)
{
  GtkWidget *window7y;
  GtkWidget *fixed7;
  GtkWidget *entry9y;
  GtkWidget *entry10y;
  GtkWidget *entry11y;
  GtkWidget *entry12y;
  GtkWidget *entry13y;
  GtkWidget *entry14y;
  GtkWidget *entry15y;
  GtkWidget *entry16y;
  GtkWidget *entry17y;
  GtkWidget *entry18y;
  GtkWidget *entry19y;
  GtkWidget *entry20y;
  GtkWidget *label37y;
  GtkWidget *label38y;
  GtkWidget *label39y;
  GtkWidget *label40y;
  GtkWidget *label41y;
  GtkWidget *label42y;
  GtkWidget *label43y;
  GtkWidget *label44y;
  GtkWidget *label45y;
  GtkWidget *label46y;
  GtkWidget *label47y;
  GtkWidget *label48y;
  GtkWidget *label49y;
  GtkWidget *label50y;
  GtkWidget *button20y;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label47;
  GtkWidget *button21y;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label48;

  window7y = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window7y), _("window7y"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window7y), fixed7);

  entry9y = gtk_entry_new ();
  gtk_widget_show (entry9y);
  gtk_fixed_put (GTK_FIXED (fixed7), entry9y, 144, 40);
  gtk_widget_set_size_request (entry9y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9y), 8226);

  entry10y = gtk_entry_new ();
  gtk_widget_show (entry10y);
  gtk_fixed_put (GTK_FIXED (fixed7), entry10y, 152, 72);
  gtk_widget_set_size_request (entry10y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10y), 8226);

  entry11y = gtk_entry_new ();
  gtk_widget_show (entry11y);
  gtk_fixed_put (GTK_FIXED (fixed7), entry11y, 112, 112);
  gtk_widget_set_size_request (entry11y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11y), 8226);

  entry12y = gtk_entry_new ();
  gtk_widget_show (entry12y);
  gtk_fixed_put (GTK_FIXED (fixed7), entry12y, 264, 160);
  gtk_widget_set_size_request (entry12y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12y), 8226);

  entry13y = gtk_entry_new ();
  gtk_widget_show (entry13y);
  gtk_fixed_put (GTK_FIXED (fixed7), entry13y, 344, 192);
  gtk_widget_set_size_request (entry13y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13y), 8226);

  entry14y = gtk_entry_new ();
  gtk_widget_show (entry14y);
  gtk_fixed_put (GTK_FIXED (fixed7), entry14y, 416, 224);
  gtk_widget_set_size_request (entry14y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14y), 8226);

  entry15y = gtk_entry_new ();
  gtk_widget_show (entry15y);
  gtk_fixed_put (GTK_FIXED (fixed7), entry15y, 144, 264);
  gtk_widget_set_size_request (entry15y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15y), 8226);

  entry16y = gtk_entry_new ();
  gtk_widget_show (entry16y);
  gtk_fixed_put (GTK_FIXED (fixed7), entry16y, 144, 304);
  gtk_widget_set_size_request (entry16y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry16y), 8226);

  entry17y = gtk_entry_new ();
  gtk_widget_show (entry17y);
  gtk_fixed_put (GTK_FIXED (fixed7), entry17y, 144, 344);
  gtk_widget_set_size_request (entry17y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry17y), 8226);

  entry18y = gtk_entry_new ();
  gtk_widget_show (entry18y);
  gtk_fixed_put (GTK_FIXED (fixed7), entry18y, 144, 384);
  gtk_widget_set_size_request (entry18y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry18y), 8226);

  entry19y = gtk_entry_new ();
  gtk_widget_show (entry19y);
  gtk_fixed_put (GTK_FIXED (fixed7), entry19y, 184, 416);
  gtk_widget_set_size_request (entry19y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry19y), 8226);

  entry20y = gtk_entry_new ();
  gtk_widget_show (entry20y);
  gtk_fixed_put (GTK_FIXED (fixed7), entry20y, 160, 456);
  gtk_widget_set_size_request (entry20y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry20y), 8226);

  label37y = gtk_label_new (_("Informations \303\240 modifier:"));
  gtk_widget_show (label37y);
  gtk_fixed_put (GTK_FIXED (fixed7), label37y, 152, 0);
  gtk_widget_set_size_request (label37y, 192, 40);

  label38y = gtk_label_new (_("Nom \303\240 modifier:"));
  gtk_widget_show (label38y);
  gtk_fixed_put (GTK_FIXED (fixed7), label38y, 0, 40);
  gtk_widget_set_size_request (label38y, 136, 24);

  label39y = gtk_label_new (_("Pr\303\251nom \303\240 modifier:"));
  gtk_widget_show (label39y);
  gtk_fixed_put (GTK_FIXED (fixed7), label39y, 0, 64);
  gtk_widget_set_size_request (label39y, 152, 40);

  label40y = gtk_label_new (_("CIN:"));
  gtk_widget_show (label40y);
  gtk_fixed_put (GTK_FIXED (fixed7), label40y, 0, 104);
  gtk_widget_set_size_request (label40y, 144, 40);

  label41y = gtk_label_new (_("Date de naissance \303\240 modifier:"));
  gtk_widget_show (label41y);
  gtk_fixed_put (GTK_FIXED (fixed7), label41y, 0, 152);
  gtk_widget_set_size_request (label41y, 216, 48);

  label42y = gtk_label_new (_("Jour:"));
  gtk_widget_show (label42y);
  gtk_fixed_put (GTK_FIXED (fixed7), label42y, 216, 168);
  gtk_widget_set_size_request (label42y, 49, 17);

  label43y = gtk_label_new (_("Mois:"));
  gtk_widget_show (label43y);
  gtk_fixed_put (GTK_FIXED (fixed7), label43y, 296, 192);
  gtk_widget_set_size_request (label43y, 49, 17);

  label44y = gtk_label_new (_("Annee:"));
  gtk_widget_show (label44y);
  gtk_fixed_put (GTK_FIXED (fixed7), label44y, 360, 224);
  gtk_widget_set_size_request (label44y, 49, 17);

  label45y = gtk_label_new (_("Sexe \303\240 modifier:"));
  gtk_widget_show (label45y);
  gtk_fixed_put (GTK_FIXED (fixed7), label45y, 0, 272);
  gtk_widget_set_size_request (label45y, 144, 16);

  label46y = gtk_label_new (_("Taille \303\240 modifier:"));
  gtk_widget_show (label46y);
  gtk_fixed_put (GTK_FIXED (fixed7), label46y, 0, 312);
  gtk_widget_set_size_request (label46y, 136, 16);

  label47y = gtk_label_new (_("Poids \303\240 modifier:"));
  gtk_widget_show (label47y);
  gtk_fixed_put (GTK_FIXED (fixed7), label47y, 8, 344);
  gtk_widget_set_size_request (label47y, 128, 24);

  label48y = gtk_label_new (_("IMC \303\240 modifier:"));
  gtk_widget_show (label48y);
  gtk_fixed_put (GTK_FIXED (fixed7), label48y, 0, 384);
  gtk_widget_set_size_request (label48y, 136, 24);

  label49y = gtk_label_new (_("Classification \303\240 modifier:"));
  gtk_widget_show (label49y);
  gtk_fixed_put (GTK_FIXED (fixed7), label49y, 0, 416);
  gtk_widget_set_size_request (label49y, 184, 32);

  label50y = gtk_label_new (_("R\303\251gime alimentaire:"));
  gtk_widget_show (label50y);
  gtk_fixed_put (GTK_FIXED (fixed7), label50y, 0, 456);
  gtk_widget_set_size_request (label50y, 160, 24);

  button20y = gtk_button_new ();
  gtk_widget_show (button20y);
  gtk_fixed_put (GTK_FIXED (fixed7), button20y, 192, 488);
  gtk_widget_set_size_request (button20y, 104, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button20y), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox14), label47, FALSE, FALSE, 0);

  button21y = gtk_button_new ();
  gtk_widget_show (button21y);
  gtk_fixed_put (GTK_FIXED (fixed7), button21y, 488, 528);
  gtk_widget_set_size_request (button21y, 92, 32);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button21y), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox15), label48, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button20y, "clicked",
                    G_CALLBACK (on_button20y_clicked),
                    NULL);
  g_signal_connect ((gpointer) button21y, "clicked",
                    G_CALLBACK (on_button21y_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window7y, window7y, "window7y");
  GLADE_HOOKUP_OBJECT (window7y, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window7y, entry9y, "entry9y");
  GLADE_HOOKUP_OBJECT (window7y, entry10y, "entry10y");
  GLADE_HOOKUP_OBJECT (window7y, entry11y, "entry11y");
  GLADE_HOOKUP_OBJECT (window7y, entry12y, "entry12y");
  GLADE_HOOKUP_OBJECT (window7y, entry13y, "entry13y");
  GLADE_HOOKUP_OBJECT (window7y, entry14y, "entry14y");
  GLADE_HOOKUP_OBJECT (window7y, entry15y, "entry15y");
  GLADE_HOOKUP_OBJECT (window7y, entry16y, "entry16y");
  GLADE_HOOKUP_OBJECT (window7y, entry17y, "entry17y");
  GLADE_HOOKUP_OBJECT (window7y, entry18y, "entry18y");
  GLADE_HOOKUP_OBJECT (window7y, entry19y, "entry19y");
  GLADE_HOOKUP_OBJECT (window7y, entry20y, "entry20y");
  GLADE_HOOKUP_OBJECT (window7y, label37y, "label37y");
  GLADE_HOOKUP_OBJECT (window7y, label38y, "label38y");
  GLADE_HOOKUP_OBJECT (window7y, label39y, "label39y");
  GLADE_HOOKUP_OBJECT (window7y, label40y, "label40y");
  GLADE_HOOKUP_OBJECT (window7y, label41y, "label41y");
  GLADE_HOOKUP_OBJECT (window7y, label42y, "label42y");
  GLADE_HOOKUP_OBJECT (window7y, label43y, "label43y");
  GLADE_HOOKUP_OBJECT (window7y, label44y, "label44y");
  GLADE_HOOKUP_OBJECT (window7y, label45y, "label45y");
  GLADE_HOOKUP_OBJECT (window7y, label46y, "label46y");
  GLADE_HOOKUP_OBJECT (window7y, label47y, "label47y");
  GLADE_HOOKUP_OBJECT (window7y, label48y, "label48y");
  GLADE_HOOKUP_OBJECT (window7y, label49y, "label49y");
  GLADE_HOOKUP_OBJECT (window7y, label50y, "label50y");
  GLADE_HOOKUP_OBJECT (window7y, button20y, "button20y");
  GLADE_HOOKUP_OBJECT (window7y, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window7y, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window7y, image14, "image14");
  GLADE_HOOKUP_OBJECT (window7y, label47, "label47");
  GLADE_HOOKUP_OBJECT (window7y, button21y, "button21y");
  GLADE_HOOKUP_OBJECT (window7y, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (window7y, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window7y, image15, "image15");
  GLADE_HOOKUP_OBJECT (window7y, label48, "label48");

  return window7y;
}

GtkWidget*
create_window8y (void)
{
  GtkWidget *window8y;
  GtkWidget *fixed8;
  GtkWidget *treeview1y;
  GtkWidget *button22y;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label49;

  window8y = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window8y), _("window8y"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (window8y), fixed8);

  treeview1y = gtk_tree_view_new ();
  gtk_widget_show (treeview1y);
  gtk_fixed_put (GTK_FIXED (fixed8), treeview1y, 56, 24);
  gtk_widget_set_size_request (treeview1y, 528, 344);

  button22y = gtk_button_new ();
  gtk_widget_show (button22y);
  gtk_fixed_put (GTK_FIXED (fixed8), button22y, 560, 400);
  gtk_widget_set_size_request (button22y, 88, 40);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button22y), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox16), label49, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button22y, "clicked",
                    G_CALLBACK (on_button22y_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window8y, window8y, "window8y");
  GLADE_HOOKUP_OBJECT (window8y, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (window8y, treeview1y, "treeview1y");
  GLADE_HOOKUP_OBJECT (window8y, button22y, "button22y");
  GLADE_HOOKUP_OBJECT (window8y, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window8y, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window8y, image16, "image16");
  GLADE_HOOKUP_OBJECT (window8y, label49, "label49");

  return window8y;
}

GtkWidget*
create_window9y (void)
{
  GtkWidget *window9y;
  GtkWidget *fixed9;
  GtkWidget *label51y;
  GtkWidget *label52y;
  GtkWidget *label53y;
  GtkWidget *label54y;
  GtkWidget *combobox6y;
  GtkWidget *combobox7y;
  GtkWidget *combobox8y;
  GtkWidget *label55y;
  GtkWidget *combobox9y;
  GtkWidget *button23y;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label55;
  GtkWidget *button24y;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label56;

  window9y = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window9y), _("window9y"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (window9y), fixed9);

  label51y = gtk_label_new (_("Disponibilit\303\251"));
  gtk_widget_show (label51y);
  gtk_fixed_put (GTK_FIXED (fixed9), label51y, 120, 0);
  gtk_widget_set_size_request (label51y, 128, 32);

  label52y = gtk_label_new (_("Jour:"));
  gtk_widget_show (label52y);
  gtk_fixed_put (GTK_FIXED (fixed9), label52y, 0, 64);
  gtk_widget_set_size_request (label52y, 49, 17);

  label53y = gtk_label_new (_("Mois:"));
  gtk_widget_show (label53y);
  gtk_fixed_put (GTK_FIXED (fixed9), label53y, 112, 64);
  gtk_widget_set_size_request (label53y, 49, 17);

  label54y = gtk_label_new (_("Annee:"));
  gtk_widget_show (label54y);
  gtk_fixed_put (GTK_FIXED (fixed9), label54y, 248, 64);
  gtk_widget_set_size_request (label54y, 49, 17);

  combobox6y = gtk_combo_box_new_text ();
  gtk_widget_show (combobox6y);
  gtk_fixed_put (GTK_FIXED (fixed9), combobox6y, 48, 56);
  gtk_widget_set_size_request (combobox6y, 48, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("01"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("02"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("03"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("04"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("05"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("06"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("07"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("08"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("09"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("20"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("21"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("23"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("24"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("25"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("26"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("27"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("28"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("29"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6y), _("31"));

  combobox7y = gtk_combo_box_new_text ();
  gtk_widget_show (combobox7y);
  gtk_fixed_put (GTK_FIXED (fixed9), combobox7y, 160, 56);
  gtk_widget_set_size_request (combobox7y, 48, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7y), _("01"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7y), _("02"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7y), _("03"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7y), _("04"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7y), _("05"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7y), _("06"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7y), _("07"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7y), _("08"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7y), _("09"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7y), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7y), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7y), _("12"));

  combobox8y = gtk_combo_box_new_text ();
  gtk_widget_show (combobox8y);
  gtk_fixed_put (GTK_FIXED (fixed9), combobox8y, 304, 56);
  gtk_widget_set_size_request (combobox8y, 48, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8y), _("2018"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8y), _("2019"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8y), _("2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8y), _("2021"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8y), _("2022"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8y), _("2023"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8y), _("2024"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8y), _("2025"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8y), _("2026"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8y), _("2027"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8y), _("2028"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8y), _("2029"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8y), _("2030"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8y), _("2031"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8y), _("2032"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8y), _("2033"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8y), _("2034"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8y), _("2035"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8y), _("2036"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8y), _("2037"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8y), _("2038"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8y), _("2039"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8y), _("2040"));

  label55y = gtk_label_new (_("Horaire:"));
  gtk_widget_show (label55y);
  gtk_fixed_put (GTK_FIXED (fixed9), label55y, 144, 104);
  gtk_widget_set_size_request (label55y, 88, 24);

  combobox9y = gtk_combo_box_new_text ();
  gtk_widget_show (combobox9y);
  gtk_fixed_put (GTK_FIXED (fixed9), combobox9y, 120, 136);
  gtk_widget_set_size_request (combobox9y, 152, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox9y), _("9h -->12h"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox9y), _("14h -->17h"));

  button23y = gtk_button_new ();
  gtk_widget_show (button23y);
  gtk_fixed_put (GTK_FIXED (fixed9), button23y, 152, 192);
  gtk_widget_set_size_request (button23y, 96, 32);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button23y), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label55 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label55);
  gtk_box_pack_start (GTK_BOX (hbox17), label55, FALSE, FALSE, 0);

  button24y = gtk_button_new ();
  gtk_widget_show (button24y);
  gtk_fixed_put (GTK_FIXED (fixed9), button24y, 312, 264);
  gtk_widget_set_size_request (button24y, 76, 32);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button24y), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label56 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label56);
  gtk_box_pack_start (GTK_BOX (hbox18), label56, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button23y, "clicked",
                    G_CALLBACK (on_button23y_clicked),
                    NULL);
  g_signal_connect ((gpointer) button24y, "clicked",
                    G_CALLBACK (on_button24y_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window9y, window9y, "window9y");
  GLADE_HOOKUP_OBJECT (window9y, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (window9y, label51y, "label51y");
  GLADE_HOOKUP_OBJECT (window9y, label52y, "label52y");
  GLADE_HOOKUP_OBJECT (window9y, label53y, "label53y");
  GLADE_HOOKUP_OBJECT (window9y, label54y, "label54y");
  GLADE_HOOKUP_OBJECT (window9y, combobox6y, "combobox6y");
  GLADE_HOOKUP_OBJECT (window9y, combobox7y, "combobox7y");
  GLADE_HOOKUP_OBJECT (window9y, combobox8y, "combobox8y");
  GLADE_HOOKUP_OBJECT (window9y, label55y, "label55y");
  GLADE_HOOKUP_OBJECT (window9y, combobox9y, "combobox9y");
  GLADE_HOOKUP_OBJECT (window9y, button23y, "button23y");
  GLADE_HOOKUP_OBJECT (window9y, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (window9y, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window9y, image17, "image17");
  GLADE_HOOKUP_OBJECT (window9y, label55, "label55");
  GLADE_HOOKUP_OBJECT (window9y, button24y, "button24y");
  GLADE_HOOKUP_OBJECT (window9y, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (window9y, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (window9y, image18, "image18");
  GLADE_HOOKUP_OBJECT (window9y, label56, "label56");

  return window9y;
}

GtkWidget*
create_window10y (void)
{
  GtkWidget *window10y;
  GtkWidget *fixed10;
  GtkWidget *treeview2y;
  GtkWidget *label59y;
  GtkWidget *button25y;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label58;

  window10y = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window10y), _("window10y"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (window10y), fixed10);

  treeview2y = gtk_tree_view_new ();
  gtk_widget_show (treeview2y);
  gtk_fixed_put (GTK_FIXED (fixed10), treeview2y, 64, 64);
  gtk_widget_set_size_request (treeview2y, 456, 288);

  label59y = gtk_label_new (_("Fiches medicales"));
  gtk_widget_show (label59y);
  gtk_fixed_put (GTK_FIXED (fixed10), label59y, 184, 8);
  gtk_widget_set_size_request (label59y, 168, 32);

  button25y = gtk_button_new ();
  gtk_widget_show (button25y);
  gtk_fixed_put (GTK_FIXED (fixed10), button25y, 456, 360);
  gtk_widget_set_size_request (button25y, 104, 40);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button25y), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label58 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox20), label58, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button25y, "clicked",
                    G_CALLBACK (on_button25y_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window10y, window10y, "window10y");
  GLADE_HOOKUP_OBJECT (window10y, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (window10y, treeview2y, "treeview2y");
  GLADE_HOOKUP_OBJECT (window10y, label59y, "label59y");
  GLADE_HOOKUP_OBJECT (window10y, button25y, "button25y");
  GLADE_HOOKUP_OBJECT (window10y, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (window10y, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (window10y, image20, "image20");
  GLADE_HOOKUP_OBJECT (window10y, label58, "label58");

  return window10y;
}

GtkWidget*
create_window11y (void)
{
  GtkWidget *window11y;
  GtkWidget *fixed11;
  GtkWidget *entry22y;
  GtkWidget *entry23y;
  GtkWidget *label63y;
  GtkWidget *entry24y;
  GtkWidget *entry25y;
  GtkWidget *label67y;
  GtkWidget *entry26y;
  GtkWidget *entry27y;
  GtkWidget *label60y;
  GtkWidget *label61y;
  GtkWidget *label62y;
  GtkWidget *label64y;
  GtkWidget *label65y;
  GtkWidget *label66y;
  GtkWidget *label68y;
  GtkWidget *label69y;
  GtkWidget *combobox10y;
  GtkWidget *button30y;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label70;
  GtkWidget *button27y;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *label69;

  window11y = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window11y), _("window11y"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (window11y), fixed11);

  entry22y = gtk_entry_new ();
  gtk_widget_show (entry22y);
  gtk_fixed_put (GTK_FIXED (fixed11), entry22y, 96, 64);
  gtk_widget_set_size_request (entry22y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry22y), 8226);

  entry23y = gtk_entry_new ();
  gtk_widget_show (entry23y);
  gtk_fixed_put (GTK_FIXED (fixed11), entry23y, 96, 104);
  gtk_widget_set_size_request (entry23y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry23y), 8226);

  label63y = gtk_label_new ("");
  gtk_widget_show (label63y);
  gtk_fixed_put (GTK_FIXED (fixed11), label63y, 24, 152);
  gtk_widget_set_size_request (label63y, 49, 17);

  entry24y = gtk_entry_new ();
  gtk_widget_show (entry24y);
  gtk_fixed_put (GTK_FIXED (fixed11), entry24y, 96, 144);
  gtk_widget_set_size_request (entry24y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry24y), 8226);

  entry25y = gtk_entry_new ();
  gtk_widget_show (entry25y);
  gtk_fixed_put (GTK_FIXED (fixed11), entry25y, 96, 224);
  gtk_widget_set_size_request (entry25y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry25y), 8226);

  label67y = gtk_label_new ("");
  gtk_widget_show (label67y);
  gtk_fixed_put (GTK_FIXED (fixed11), label67y, 32, 272);
  gtk_widget_set_size_request (label67y, 49, 17);

  entry26y = gtk_entry_new ();
  gtk_widget_show (entry26y);
  gtk_fixed_put (GTK_FIXED (fixed11), entry26y, 96, 264);
  gtk_widget_set_size_request (entry26y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry26y), 8226);

  entry27y = gtk_entry_new ();
  gtk_widget_show (entry27y);
  gtk_fixed_put (GTK_FIXED (fixed11), entry27y, 96, 304);
  gtk_widget_set_size_request (entry27y, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry27y), 8226);

  label60y = gtk_label_new (_("Informations personnelles"));
  gtk_widget_show (label60y);
  gtk_fixed_put (GTK_FIXED (fixed11), label60y, 144, 0);
  gtk_widget_set_size_request (label60y, 216, 56);

  label61y = gtk_label_new (_("Nom:"));
  gtk_widget_show (label61y);
  gtk_fixed_put (GTK_FIXED (fixed11), label61y, 8, 64);
  gtk_widget_set_size_request (label61y, 72, 24);

  label62y = gtk_label_new (_("Prenom:"));
  gtk_widget_show (label62y);
  gtk_fixed_put (GTK_FIXED (fixed11), label62y, 8, 104);
  gtk_widget_set_size_request (label62y, 80, 24);

  label64y = gtk_label_new (_("Age:"));
  gtk_widget_show (label64y);
  gtk_fixed_put (GTK_FIXED (fixed11), label64y, 24, 152);
  gtk_widget_set_size_request (label64y, 49, 17);

  label65y = gtk_label_new (_("Sexe:"));
  gtk_widget_show (label65y);
  gtk_fixed_put (GTK_FIXED (fixed11), label65y, 24, 192);
  gtk_widget_set_size_request (label65y, 49, 17);

  label66y = gtk_label_new (_("Adresse:"));
  gtk_widget_show (label66y);
  gtk_fixed_put (GTK_FIXED (fixed11), label66y, 0, 224);
  gtk_widget_set_size_request (label66y, 96, 32);

  label68y = gtk_label_new (_("Tel:"));
  gtk_widget_show (label68y);
  gtk_fixed_put (GTK_FIXED (fixed11), label68y, 24, 272);
  gtk_widget_set_size_request (label68y, 49, 17);

  label69y = gtk_label_new (_("Email:"));
  gtk_widget_show (label69y);
  gtk_fixed_put (GTK_FIXED (fixed11), label69y, 16, 304);
  gtk_widget_set_size_request (label69y, 72, 24);

  combobox10y = gtk_combo_box_new_text ();
  gtk_widget_show (combobox10y);
  gtk_fixed_put (GTK_FIXED (fixed11), combobox10y, 96, 184);
  gtk_widget_set_size_request (combobox10y, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox10y), _("femme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox10y), _("homme"));

  button30y = gtk_button_new ();
  gtk_widget_show (button30y);
  gtk_fixed_put (GTK_FIXED (fixed11), button30y, 64, 360);
  gtk_widget_set_size_request (button30y, 176, 32);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (button30y), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label70 = gtk_label_new_with_mnemonic (_("Ajouter/Modifier"));
  gtk_widget_show (label70);
  gtk_box_pack_start (GTK_BOX (hbox22), label70, FALSE, FALSE, 0);

  button27y = gtk_button_new ();
  gtk_widget_show (button27y);
  gtk_fixed_put (GTK_FIXED (fixed11), button27y, 392, 360);
  gtk_widget_set_size_request (button27y, 112, 40);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (button27y), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  label69 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label69);
  gtk_box_pack_start (GTK_BOX (hbox21), label69, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) window11y, "show",
                    G_CALLBACK (on_window11y_show),
                    NULL);
  g_signal_connect ((gpointer) button30y, "clicked",
                    G_CALLBACK (on_button30y_clicked),
                    NULL);
  g_signal_connect ((gpointer) button27y, "clicked",
                    G_CALLBACK (on_button27y_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window11y, window11y, "window11y");
  GLADE_HOOKUP_OBJECT (window11y, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (window11y, entry22y, "entry22y");
  GLADE_HOOKUP_OBJECT (window11y, entry23y, "entry23y");
  GLADE_HOOKUP_OBJECT (window11y, label63y, "label63y");
  GLADE_HOOKUP_OBJECT (window11y, entry24y, "entry24y");
  GLADE_HOOKUP_OBJECT (window11y, entry25y, "entry25y");
  GLADE_HOOKUP_OBJECT (window11y, label67y, "label67y");
  GLADE_HOOKUP_OBJECT (window11y, entry26y, "entry26y");
  GLADE_HOOKUP_OBJECT (window11y, entry27y, "entry27y");
  GLADE_HOOKUP_OBJECT (window11y, label60y, "label60y");
  GLADE_HOOKUP_OBJECT (window11y, label61y, "label61y");
  GLADE_HOOKUP_OBJECT (window11y, label62y, "label62y");
  GLADE_HOOKUP_OBJECT (window11y, label64y, "label64y");
  GLADE_HOOKUP_OBJECT (window11y, label65y, "label65y");
  GLADE_HOOKUP_OBJECT (window11y, label66y, "label66y");
  GLADE_HOOKUP_OBJECT (window11y, label68y, "label68y");
  GLADE_HOOKUP_OBJECT (window11y, label69y, "label69y");
  GLADE_HOOKUP_OBJECT (window11y, combobox10y, "combobox10y");
  GLADE_HOOKUP_OBJECT (window11y, button30y, "button30y");
  GLADE_HOOKUP_OBJECT (window11y, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (window11y, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (window11y, image22, "image22");
  GLADE_HOOKUP_OBJECT (window11y, label70, "label70");
  GLADE_HOOKUP_OBJECT (window11y, button27y, "button27y");
  GLADE_HOOKUP_OBJECT (window11y, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (window11y, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (window11y, image21, "image21");
  GLADE_HOOKUP_OBJECT (window11y, label69, "label69");

  return window11y;
}

GtkWidget*
create_window12y (void)
{
  GtkWidget *window12y;
  GtkWidget *fixed12;
  GtkWidget *treeview3y;
  GtkWidget *label80y;
  GtkWidget *button40y;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image23;
  GtkWidget *label72;

  window12y = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window12y), _("window12y"));

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (window12y), fixed12);

  treeview3y = gtk_tree_view_new ();
  gtk_widget_show (treeview3y);
  gtk_fixed_put (GTK_FIXED (fixed12), treeview3y, 48, 32);
  gtk_widget_set_size_request (treeview3y, 520, 248);

  label80y = gtk_label_new (_("Liste des rendez-vous"));
  gtk_widget_show (label80y);
  gtk_fixed_put (GTK_FIXED (fixed12), label80y, 200, 0);
  gtk_widget_set_size_request (label80y, 232, 24);

  button40y = gtk_button_new ();
  gtk_widget_show (button40y);
  gtk_fixed_put (GTK_FIXED (fixed12), button40y, 488, 336);
  gtk_widget_set_size_request (button40y, 104, 40);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (button40y), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image23 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox23), image23, FALSE, FALSE, 0);

  label72 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label72);
  gtk_box_pack_start (GTK_BOX (hbox23), label72, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button40y, "clicked",
                    G_CALLBACK (on_button40y_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window12y, window12y, "window12y");
  GLADE_HOOKUP_OBJECT (window12y, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (window12y, treeview3y, "treeview3y");
  GLADE_HOOKUP_OBJECT (window12y, label80y, "label80y");
  GLADE_HOOKUP_OBJECT (window12y, button40y, "button40y");
  GLADE_HOOKUP_OBJECT (window12y, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (window12y, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (window12y, image23, "image23");
  GLADE_HOOKUP_OBJECT (window12y, label72, "label72");

  return window12y;
}

