/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1y (void);
GtkWidget* create_window2y (void);
GtkWidget* create_window3y (void);
GtkWidget* create_window4y (void);
GtkWidget* create_window5y (void);
GtkWidget* create_window6y (void);
GtkWidget* create_window7y (void);
GtkWidget* create_window8y (void);
GtkWidget* create_window9y (void);
GtkWidget* create_window10y (void);
GtkWidget* create_window11y (void);
GtkWidget* create_window12y (void);
